### PR TITLE
{tools}[GCCcore/8.3.0] hypothesis v4.44.2 w/ Python 3.7.4

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/15ea0711ef6640bb5f47ae8a65f68951 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bear-pg0211u13a.bear.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, Python 2.7.5
See https://gist.github.com/571c88b0f5c9e6060394e90050c2ca62 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
bb2c1a09.bb2.cluster - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/27e0b8ac130f58246c7c29ba40dea997 for a full test report.

File: easybuild/easyconfigs/h/hypothesis/hypothesis-4.44.2-GCCcore-8.3.0-Python-3.7.4.eb [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+homepage = "https://github.com/HypothesisWorks/hypothesis"
+description = """Hypothesis is an advanced testing library for Python. It lets you write tests which are parametrized
+ by a source of examples, and then generates simple and comprehensible examples that make your tests fail. This lets
+ you find more bugs in your code with less work."""
+
+toolchain = {'name': 'GCCcore', 'version': '8.3.0'}
+
+builddependencies = [('binutils', '2.32')]
+
+dependencies = [('Python', '3.7.4')]
```
Comment (smoors) [inline easybuild/easyconfigs/h/hypothesis/hypothesis-4.44.2-GCCcore-8.3.0-Python-3.7.4.eb]: @branfosj hypothesis still works with Python 2, no?
in that case please use `multi_deps` as was done for `hypothesis-4.23.4-GCCcore-8.2.0.eb`?
(see also the email of Kenneth to the mailing list from 1 day ago)

Comment (branfosj) [reply easybuild/easyconfigs/h/hypothesis/hypothesis-4.44.2-GCCcore-8.3.0-Python-3.7.4.eb]: I've just tried to `multi_deps` it and I'm hitting an odd error: https://gist.github.com/branfosj/61a8bf5135f2cc422c1f8d545b5da7f3

https://gist.github.com/branfosj/61a8bf5135f2cc422c1f8d545b5da7f3#file-easybuild-hypothesis-4-44-2-20191116-190723-sallh-log-L1124 shows: `TypeError: attrs() got an unexpected keyword argument 'eq'` which is unexpected. This feature got added to `attrs` in 19.2 but I'm using 19.3 here, which suggests that we're picking up the `attrs` 19.1 that is included in the Python 2.7.16 and 3.7.4 installs instead. However, this doesn't happen when I build the Python 3.7.4 specific hypothesis module.

And,
```
diff -r ../../../../../../EL7/EL7-cascadelake/software/hypothesis/4.44.2-GCCcore-8.3.0-Python-3.7.4/lib/python3.7/site-packages/ ../../../../../../EL7/EL7-cascadelake/software/hypothesis/4.44.2-GCCcore-8.3.0/lib/python3.7/site-packages/
```
shows that the two `lib/python3.7/site-packages` directories are identical.

I'm running at version 4.0.1 for framework, easyblocks, and easyconfigs.

Comment (boegel) [reply easybuild/easyconfigs/h/hypothesis/hypothesis-4.44.2-GCCcore-8.3.0-Python-3.7.4.eb]: You can't easily override a Python package from the `Python` installation when using `multi_deps`, we've run into that earlier this week for something else, basically because for `multi_deps` to work we don't use `$PYTHONPATH` but [site.addsitedir](https://docs.python.org/3/library/site.html#site.addsitedir), and apparently the latter only append, there is no way to prepend (see also https://bugs.python.org/issue7744).

So I guess we'll have to go forward with Python 3-only here.

Is this a dependency for something else?

Comment (branfosj) [reply easybuild/easyconfigs/h/hypothesis/hypothesis-4.44.2-GCCcore-8.3.0-Python-3.7.4.eb]: I've started work on PyTorch 1.3.1 and this is for that. The pull requests I have done today are all in support of that.

Comment (boegel) [reply easybuild/easyconfigs/h/hypothesis/hypothesis-4.44.2-GCCcore-8.3.0-Python-3.7.4.eb]: We're stuck to a single `Python` version there anyway, due to `SciPy-bundle`, so OK.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2630.swalot.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/754cffd4545c0012748e42366fafa986 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/63d5beb70d786e9aed0fe8ae6e3e463c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3146.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/bac6d86cee04933a152c50cbaab96ebf for a full test report.

**Comment by boegel** [comment]
@smoors OK to merge?

**Comment by akesandgren** [comment]
@branfosj Does this version of hypothesis depend on attrs >= 19.2 then?

**Comment by branfosj** [comment]
Yes. `hypothesis` 4.38.2 bumped the required `attrs` to `>=19.2.0` - https://hypothesis.readthedocs.io/en/latest/changes.html#v4-38-2 

For PyTorch I believe that I do not need such a recent `hypothesis`, so there is an option to go with `4.37.0` instead and `multi_deps` it.

**Comment by akesandgren** [comment]
Ok, then let's go with this one ....

**Comment by akesandgren** [comment]
Going in, thanks @branfosj!

**Comment by akesandgren** [comment]
Going in, thanks @branfosj!

**Comment by akesandgren** [comment]
Going in, thanks @branfosj!
