### PR TITLE
{data,lib}[GCCcore/8.3.0,intel/2019b] NCL v6.6.2, libiconv v1.16

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
requires ~~#9508~~ (makedepend), ~~#9506~~ (g2lib,g2clib), ~~#9505~~ (HDF), ~~#9512~~ (GDAL), ~~#9507~~ (UDUNITS), ~~#9513~~ (ESMF), ~~#9514~~ (cairo)

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/c77e089bfa22475b86d7da2efd4fba30 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2407.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/4cfabdc208824c5eca492e306697c516 for a full test report.

**Comment by migueldiascosta** [comment]
closing and reopening to trigger tests

**Comment by migueldiascosta** [comment]
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/6c7347ef02d69d7fe77bea8493a37922 for a full test report.

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 19 out of 23 (2 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/fb3000713953bff15fdef17c39cdee18 for a full test report.

**Comment by smoors** [comment]
build error for g2lib:
```
gfortran -c -O2 -ftree-vectorize -march=native -fno-math-errno -fno-range-check -I. jpcunpack.f
ar  -ruv libg2.a jpcunpack.o
a - jpcunpack.o
rm -f jpcunpack.o
gcc -c -O2 -ftree-vectorize -march=native -fno-math-errno -DLINUXG95 -D__64BIT__ enc_jpeg2000.c
enc_jpeg2000.c:4:10: fatal error: jasper/jasper.h: No such file or directory
 #include "jasper/jasper.h"
          ^~~~~~~~~~~~~~~~~
```

**Comment by smoors** [comment]
this is odd.
g2lib-3.1.0 builds fine with GCCcore-8.2.0 but fails with GCCcore-8.3.0

**Comment by boegel** [comment]
@smoors Looks like this could be caused by the bug introduced in https://github.com/easybuilders/easybuild-framework/pull/3145?
Does the `JasPer` module with `GCCcore/.8.3.0` still update `$CPATH`?

**Comment by boegel** [comment]
> this is odd.
> g2lib-3.1.0 builds fine with GCCcore-8.2.0 but fails with GCCcore-8.3.0

fix in https://github.com/easybuilders/easybuild-framework/pull/3145 is merged, please update `easybuild-framework` to latest `develop`, do a forced reinstall of `JasPer` (so the module updates `$CPATH`), and try again...

**Comment by smoors** [comment]
Test report by @smoors
**FAILED**
Build succeeded for 19 out of 22 (2 easyconfigs in this PR)
node372.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c5f154788a56ec30db8ababe64370378 for a full test report.

**Comment by smoors** [comment]
@boegel g2lib builds fine with the fix, but the GEOS build failed:
```
icpc -DHAVE_CONFIG_H -I. -I../../include   -I/apps/brussel/CO7/skylake/software/Python/3.7.4-GCCcore-8.3.0/include -DGEOS_INLINE  -Wsuggest-override -Wmissing-override -pedantic -Wall -Wno-long-long  -ffloat-store -DUSE_UNSTABLE_GEOS_CPP_API -O2 -xHost -ftz -fp-speculation=safe -fp-model source -MT ASLocalizer.o -MD -MP -MF $depbase.Tpo -c -o ASLocalizer.o ASLocalizer.cpp &&\
mv -f $depbase.Tpo $depbase.Po
icpc: command line warning #10148: option '-Wsuggest-override' not supported
icpc: command line warning #10148: option '-Wmissing-override' not supported
icpc: command line warning #10148: option '-Wsuggest-override' not supported
icpc: command line warning #10148: option '-Wmissing-override' not supported
icpc: command line warning #10148: option '-Wsuggest-override' not supported
icpc: command line warning #10148: option '-Wmissing-override' not supported
icpc: command line warning #10148: option '-Wsuggest-override' not supported
icpc: command line warning #10148: option '-Wmissing-override' not supported
ASLocalizer.cpp(411): error #913: invalid multibyte character sequence
  >-addPair("Formatted  %s\n", L"  %s\n");>->---// should align with unchanged
  >-                             ^
...
```

**Comment by smoors** [comment]
@boegel adding `toolchainopts = {'cstd': 'c++11'}` fixes it for me, see #9625

**Comment by smoors** [comment]
Test report by @smoors
**SUCCESS**
Build succeeded for 22 out of 22 (2 easyconfigs in this PR)
node374.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/5a7aacdfe68f2bfdb800a7070a1f90eb for a full test report.

**Comment by smoors** [comment]
Going in, thanks @boegel!
