### PR TITLE
{math}[NVHPC/25.3-CUDA-12.8.0] ELPA v2025.06.002

### PR DESCRIPTION
**Pull request by pavelToman**
(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/571
requires:
- https://github.com/easybuilders/easybuild-easyblocks/pull/4051
- https://github.com/easybuilders/easybuild-framework/pull/5093

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 4051"

**Comment by boegel** [comment]
@pavelToman Can you take a look at the test failure, what am I overlooking?

**Comment by pavelToman** [comment]
> Test report by @boegelbot Using easyblocks from PR(s) [easybuilders/easybuild-easyblocks#4051](https://github.com/easybuilders/easybuild-easyblocks/pull/4051) **FAILED** Build succeeded for 0 out of 1 (total: 20 secs) (1 easyconfigs in total) jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.7, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.23 See https://gist.github.com/boegelbot/f26c3b4f7bb0981e2b8dcc8511f95b9b for a full test report.

The error:
```
build_log.py:233 ERROR EasyBuild encountered an error: 
List of toolchain dependency modules and toolchain definition do not match 
(found ['GCCcore/14.2.0', 'binutils/2.42-GCCcore-14.2.0', 'numactl/2.0.19-GCCcore-14.2.0', 'CUDA/12.8.0'] 
vs expected {'nvidia-compilers'}) 
(at easybuild/easybuild-framework/easybuild/tools/toolchain/toolchain.py:793 in _verify_toolchain)
```

@boegel @lexming do you know what is going on ?

**Comment by pavelToman** [comment]
Test report by @pavelToman
**SUCCESS**
Build succeeded for 1 out of 1 (total: 1 hour 32 mins 36 secs) (1 easyconfigs in total)
node4007.donphan.os - Linux RHEL 9.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 580.95.05, Python 3.9.21
See https://gist.github.com/pavelToman/929b99c461f8db6b9605ff1910361697 for a full test report.

**Comment by Thyre** [comment]
Maybe caused by #25120? I'll try a rebuild of NVHPC + ELPA in a temp location.

**Comment by Thyre** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 4051 NVHPC-25.3-CUDA-12.8.0.eb ELPA-2025.06.002-NVHPC-25.3-CUDA-12.8.0.eb --installpath /tmp/$USER/ecpr-25147"

**Comment by Thyre** [comment]
Okay, this fixes the issue seen before. So the prior failure occurs with "old" NVHPC installations.

We now very likely hit the issue solved by https://github.com/easybuilders/easybuild-framework/pull/5093

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
I see the issue here is that `jsc-zen3` has a deprecated install of `NVHPC-25.3-CUDA-12.8.0.eb` that still uses the older toolchain withour `nvidia-compilers`. Rebuilding should fix it.

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="NVHPC-25.3-CUDA-12.8.0.eb ELPA-2025.06.002-NVHPC-25.3-CUDA-12.8.0.eb"

File: easybuild/easyconfigs/e/ELPA/ELPA-2025.06.002-NVHPC-25.3-CUDA-12.8.0.eb [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+builddependencies = [
+    ('Python', '3.13.1'),
+    ('Perl', '5.40.0'),
+]
+dependencies = [('CUDA', '12.8.0', '', SYSTEM)]
+
+preconfigopts = 'export LDFLAGS="-lm $LDFLAGS" && '
+configopts = '--without-threading-support-check-during-build --enable-allow-thread-limiting '
+configopts += '--enable-runtime-threading-support-checks '
```
Comment (lexming) [inline easybuild/easyconfigs/e/ELPA/ELPA-2025.06.002-NVHPC-25.3-CUDA-12.8.0.eb]: @pavelToman this is new, can you add a comment about why is this needed? is this only for NVHPC or for any toolchain?

Comment (pavelToman) [reply easybuild/easyconfigs/e/ELPA/ELPA-2025.06.002-NVHPC-25.3-CUDA-12.8.0.eb]: other toolchains works ok without those flags, it seems as a problem of NVHPC toolchain and its MPI plus `--enable-openmp`.

Comment (pavelToman) [reply easybuild/easyconfigs/e/ELPA/ELPA-2025.06.002-NVHPC-25.3-CUDA-12.8.0.eb]: the error from configure:
```
configure: ************************************************************************************************************************** 
configure: * Please notice if the following step hangs or aborts abnormaly then you cannot run a short MPI-program during configure 
* configure: * In this case please re-run configure with '--without-threading-support-check-during-build' _AND_ follow the hints in 
* configure: * the INSTALL and USER_GUIDE documents! 
* configure: * In case you get some other warnings about threading support follow on of the steps detailed there 
* configure: ************************************************************************************************************************** 
checking what threading level is supported by the MPI library... no 
configure: WARNING: Your MPI implementation does not provide a sufficient threading level for OpenMP 
configure: WARNING: You do have several options: 
configure: WARNING: * disable OpenMP (--disable-openmp): this will ensure correct results, but maybe some performance drop 
configure: WARNING: * use an MPI-library with the required threading support level (see the INSTALL and USER_GUIDE): this will 
configure: WARNING: ensure correct results and best performance 
configure: WARNING: * allow ELPA at runtime to change the number of threads to 1 by setting "--enable-runtime-threading-support-checks 
configure: WARNING: --enable-allow-thread-limiting --without-threading-support-check-during-build": this will ensure correct results, but 
configure: WARNING: maybe not the best performance (depends on the threading of your blas/lapack libraries), see the USER_GUIDE 
configure: WARNING: * switch of the checking of threading support "--disable-runtime-threading-support-checks configure: 
WARNING: --without-threading-support-check-during-build: DO THIS AT YOUR OWN RISK! This will be fast, but might configure: WARNING: (depending on your MPI library sometimes) lead to wrong results 
configure: error: You do have to take an action of the choices above!
```

Comment (lexming) [reply easybuild/easyconfigs/e/ELPA/ELPA-2025.06.002-NVHPC-25.3-CUDA-12.8.0.eb]: thanks for the explanation 👍

**Comment by lexming** [comment]
@boegelbot please test @ jsc-zen3

**Comment by lexming** [comment]
Merging, thanks @pavelToman !
