### ISSUE TITLE
Qt5/5.15.5-GCCcore-11.3.0 fails to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by bedroge** [easybuilders/easybuild-easyconfigs#17059]
During the build of `Qt5/5.15.5-GCCcore-11.3.0` on my Ubuntu 22.04 system, I got the following error:
```
/failure_signal_handler.cc: In function 'bool absl::SetupAlternateStackOnce()':
../../../../git/src/3rdparty/chromium/third_party/abseil-cpp/absl/debugging/failure_signal_handler.cc:138:32: error: no matching function for call to 'max(long int, int)'
```

Apparently, it's related to the glibc version:
https://bugs.gentoo.org/811312
That bug report also contains two patches, and they solved the issue for me. I don't know if it makes sense to always include them in the easyconfig, but at least I wanted to report the issue here in case other people run into the same issue.

**Comment by boegel** [comment]
@bedroge Do you mind opening a PR to add those patches, so we can test on other operating systems too?

As long as the patches don't cause trouble with older glibc version, we can always include them (cfr. #13730)

**Comment by bedroge** [comment]
> @bedroge Do you mind opening a PR to add those patches, so we can test on other operating systems too?
> 
> As long as the patches don't cause trouble with older glibc version, we can always include them (cfr. #13730)

@boegel: done in #17165.
