### ISSUE TITLE
M4 v1.20.0 fails to build with recent glibc (v2.43)

### ISSUE THREAD

**Issue by Thyre** [easybuilders/easybuild-easyconfigs#26249]
M4 v1.20.0, used in 2025a, 2025b and 2026.1, fails to build with a very recent glibc (e.g., v2.43). 
A build of `M4-1.4.20.eb` fails with:

```
In file included from /usr/include/features.h:540,
                 from /usr/include/errno.h:25,
                 from openat-priv.h:23,
                 from openat-proc.c:22:
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
In file included from /usr/include/features.h:540,
                 from ./wchar.h:69,
                 from btowc.c:21:
./string.h:777:20: error: expected identifier or '(' before '_Generic'
  777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
      |                    ^~~~~~
./wchar.h:838:23: error: expected identifier or '(' before '_Generic'
  838 | _GL_EXTERN_C wchar_t *wmemchr (const wchar_t *__s, wchar_t __wc, size_t __n)
      |                       ^~~~~~~
In file included from /usr/include/features.h:540,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from ./string.h:41,
                 from basename-lgpl.c:24:
./string.h:777:20: error: expected identifier or '(' before '_Generic'
  777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
      |                    ^~~~~~
In file included from /usr/include/features.h:540,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:26,
                 from ./stdlib.h:51,
                 from gl_avltree_oset.c:23:
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
make[3]: *** [Makefile:4156: libm4_a-basename-lgpl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:4142: libm4_a-gl_avltree_oset.o] Error 1
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
./string.h:777:20: error: expected identifier or '(' before '_Generic'
  777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
      |                    ^~~~~~
make[3]: *** [Makefile:4198: libm4_a-btowc.o] Error 1
In file included from /usr/include/features.h:540,
                 from /usr/include/sys/types.h:25,
                 from ./sys/types.h:46,
                 from ./signal.h:49,
                 from asyncsafe-spin.h:43,
                 from asyncsafe-spin.c:22:
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
make[3]: *** [Makefile:4128: libm4_a-openat-proc.o] Error 1
make[3]: *** [Makefile:4114: libm4_a-asyncsafe-spin.o] Error 1
```

The issue is resolved with M4 v1.4.21. See also #26247. However, this blocks users from recent glibc versions from building all currently available toolchains.

We might be able to come up with a patch, but diffing both versions, it looks like most of the changes were pulled in from updating the `gnulib` submodule. Hence, we'd need to port these changes manually.

Simply changing the C standard is not sufficient.

**Comment by Thyre** [comment]
Affected distributions:

- Ubuntu 26.04 LTS
- Arch Linux
- Fedora 44

OpenSUSE, Rocky 10 and others are still below glibc 2.43, hence should not run into this issue.
