### ISSUE TITLE
NAMD/2.14 with intel/2020a fails compilation

### ISSUE THREAD

**Issue by zao** [easybuilders/easybuild-easyconfigs#12588]
Build log: https://gist.github.com/zao/b11c7d129c1fca9b9e2a2cfb0152d983

`NAMD-2.14-intel-2020a-mpi.eb` fails to build on my Ubuntu 20.04 on a Coffee Lake 8700K when building a bundled Charm++ as shown in the log above with multiple instances of errors like this:
```
../bin/charmc  -optimize -production  -O2 -xHost -ftz -fp-speculation=safe -fp-model source -fPIC -DMPICH_IGNORE_CXX_SEEK -fpermissive  -I. -o ../lib/libmemory-gnu-paranoid.a -DCMK_MEMORY_BUILD_PARANOID -touch-on-failure libmemory-gnu-paranoid.o
Fatal Error by charmc in directory /tmp/eb-build/NAMD/2.14/intel-2020a-mpi/NAMD_2.14_Source/charm-6.10.2/mpi-linux-x86_64-mpicxx/tmp
   libmemory-gnu.o: file not recognized: File truncated
charmc exiting...
make: *** [Makefile:685: ../lib/libmemory-gnu.a] Error 1
make: *** Waiting for unfinished jobs....
In file included from memory-gnu.C(87),
                 from memory-leak.C(21),
                 from memory.C(663):
memory-gnu-internal.C(1495): error: allowing all exceptions is incompatible with previous function "mremap" (declared at line 133 of "/usr/include/x86_64-linux-gnu/sys/mman.h")
               size_t new_size, int flags, ... );
                                                ^

compilation aborted for memory.C (code 2)
```

The declaration of `mremap` in the system header is:
```c
extern void *mremap (void *__addr, size_t __old_len, size_t __new_len,
                     int __flags, ...) __THROW;
```

I don't seem to find which PR if any that introduced this easyconfig so I can't see any previous test reports for systems like mine - all I can find is the adding commit 797ea75d2d6a82eb25dd922b890e3503947e84b8.

`NAMD-2.14-foss-2020a-mpi.eb` and `NAMD-2.14-foss-2019b-mpi.eb` build fine.

**Comment by branfosj** [comment]
#11114 is the NAMD 2.14 Intel 2020a PR.

**Comment by zao** [comment]
The problem may have been addressed in the upstream charm++ `main` branch by commit https://github.com/UIUC-PPL/charm/commit/26ef223352336541781b994022f79439a76f74eb which uses the OS declaration instead of declaring the signature themselves, there might be some commits that can be backported to the NAMD build.

I see that the NAMD easyblock unpacks the charm++ tarball early so that it can be patched, so this may be easy to achieve.

**Comment by Micket** [comment]
fixed by #12594
