### PR TITLE
fix for "error: 'runtime_error' is not a member of 'std'" in qtlocation for Qt5 v5.14.2

### PR DESCRIPTION
**Pull request by branfosj**
(created using `eb --new-pr`)

`Qt5-5.14.2-GCCcore-10.2.0.eb` fails to build on CentOS 7.8 for me with the message: `error: 'runtime_error' is not a member of 'std'`

This unpatched version built OK on CentOS 8.2 for me - though we do have differences in available OS packages between CentOS 7 and 8..

### CODE REVIEW

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u38b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/1534d6b203da4adcdce444301b368004 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/f054cf8b559965fed44a05be5aef60e4 for a full test report.

**Comment by boegel** [comment]
@branfosj Any ideas why this didn't pop up in #11555, where we also tested on CentOS 7.8? :-/

**Comment by branfosj** [comment]
My thoughts were that it is to do with OS packages being detected and that these are causing additional Qt5 components to be installed in my case.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3509.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/957a017403d213f21ad264df511ddea7 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2678.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3687ca24586897863299be1130f65680 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3115.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/2f87fa89e55d49cf8d7312cdf31def5a for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @branfosj!

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2318
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/016d4be4cd0b82f1347e3fb2f96f173a for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2318
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.7
See https://gist.github.com/970b7484d65eb6bc0b2efdd5250eaaa0 for a full test report.
