### ISSUE TITLE
automake 1.15 build fails if PERL's `Thread::Queue` is not available

### ISSUE THREAD

**Issue by riccardomurri** [easybuilders/easybuild-easyconfigs#1822]
When trying to build `automake` (as a dependency to build `R` with the `foss-2015a` toolchain), I ran into an error stating that "help2man cannot run automake-1.15 --help".

It turned out that a previous "make bootstrap" phase had failed, because PERL module `Thread::Queue` was not installed on the system, and autoconf/autom4te depends on it.

**Comment by riccardomurri** [comment]
This is the actual log excerpt with the error::

        == 2015-08-04 07:38:57,622 main.ConfigureMake INFO Starting build step
        == 2015-08-04 07:38:57,624 main.ConfigureMake INFO Running method build_step part of step build
        == 2015-08-04 07:38:58,235 main ERROR cmd " make -j 4 " exited with exitcode 2 and output:
          GEN      bin/automake
          GEN      bin/aclocal
          GEN      t/ax/shell-no-trail-bslash
          GEN      t/ax/cc-no-c-o
          GEN      doc/aclocal.1
          GEN      runtest
          GEN      doc/automake.1
          GEN      lib/Automake/Config.pm
          GEN      t/ax/test-defs.sh
          GEN      doc/aclocal-1.15.1
          GEN      doc/automake-1.15.1
        help2man: can't get `--help' info from automake-1.15
        Try `--no-discard-stderr' if option outputs to stderr
        make: *** [doc/automake-1.15.1] Errore 2
        make: *** Attesa dei processi non terminati....
         (at easybuild/software/EasyBuild/2.2.0/lib/python2.7/site-packages/easybuild_framework-2.2.0-py2.7.egg/easybuild/tools/run.py:360 in parse_cmd_output)
        == 2015-08-04 07:38:58,237 main.easyblock WARNING build failed (first 300 chars): cmd " make -j 4 " exited with exitcode 2 and output:

**Comment by rjeschmi** [comment]
Same problem. Thanks for the fix (I guess we should add it as an OS dep or soemthing?)

**Comment by boegel** [comment]
Making it a OS dep would help in catching this.

The other alternative is to add a Perl version that provides `Thread::Queue` as a dependency for Automake...

**Comment by fgeorgatos** [comment]
+1 , bitten by it once more today ;-)

IMHO, making failed documentation steps to block the complete build process is not appropriate nor is it to chain underneath a full build of Perl (or that should be a tunable).

Anyway, for the time being the solution on my end -for a Fedora/22 box- has been: 
`dnf install perl-Thread-Queue.noarch`

**Comment by rjeschmi** [comment]
@fgeorgatos I don't understand what you think is appropriate. Do you disagree with making the OS dep?

**Comment by fgeorgatos** [comment]
@rjeschmi : 

I have seen again other builds fail due to a missing documentation build step (typically perl), and I put forward the question if we should really consider that a blocker. Ideally, I'd like that to be chosen!
(we need not stop what we do today, with osdeps, just consider if we can do it better)

**Comment by rjeschmi** [comment]
I like that I ran into this again tonight and I could still google this.

I guess we are still missing an os dep check...

**Comment by damianam** [comment]
+1 to the number of people bitten by this :-P

**Comment by boegel** [comment]
`Thread::Queue` is a Perl core module, but maybe the system Perl was too old?

@damianam Did you very whether you were hitting the exact same problem? If so, what is the version of the OS-provided Perl? I can't seem to find since when `Thread::Queue` is a core module.

We can consider include a `-bare` Perl installation as a build dep for `Autoconf`, but that is going to cause headaches when `Autoconf` or `Automake` are used in a situation where another Perl is used as a dependency...

**Comment by damianam** [comment]
`Thread::Queue` is a perl core module in Scientific Linux 6.8, but in CentOS 7.2 and 7.3 you need `perl-Thread-Queue`. I asked the admins to install it and it seems to fix the issue.

**Comment by boegel** [comment]
Wait, if it's a *core* Perl module, which did they split it off into a separate package? :-/

I guess we can consider including `Thread::Queue` as an extension in `Autoconf`?

**Comment by damianam** [comment]
Well, my perl ignorance is remarkable. I don't know if it is a **perl core** module. I just now that that particular module is included in the perl package with SL.

**Comment by boegel** [comment]
It is a core module, at least now, see http://perldoc.perl.org/Thread/Queue.html

**Comment by damianam** [comment]
We have Perl 5.16.3 in the system where that failed (CentOS 7.3). According to the docs, it was also a core module there: http://perldoc.perl.org/5.16.2/Thread/Queue.html I don't know why it isn't included there.

**Comment by thecuf** [comment]
HI
same problem in compiling :+1: 

root@LinuxDebianDevelop:/home/alfredo/added_libraries/automake-1.15# make
  GEN      doc/automake-1.15.1
help2man: can't get `--help' info from automake-1.15
Try `--no-discard-stderr' if option outputs to stderr
Makefile:3687: recipe for target 'doc/automake-1.15.1' failed
make: *** [doc/automake-1.15.1] Error 2
root@LinuxDebianDevelop:/home/alfredo/added_libraries/automake-1.15# perl --version

This is perl 5, version 26, subversion 0 (v5.26.0) built for i686-linux-thread-multi-ld

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

But it seems that threading is ok.  Any idea ? Results for uname -a is:
Linux LinuxDebianDevelop 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2 (2017-04-30) i686 GNU/Linux

regards

**Comment by boegel** [comment]
@thecuf What does `perl -e 'use Thread::Queue'; echo $?` print?

**Comment by thecuf** [comment]
Hi
result is this:
root@LinuxDebianDevelop:/home/alfredo/added_libraries/automake-1.15# perl -e 'use Thread::Queue'; echo $? 
0

It seems that use Thread queue is disabled. I compiled perl with :+1: 
./Configure -des -Dusethreads

and all goes ok (make tests and make install). How can I enable use Thread::Queue ?

regards

**Comment by boegel** [comment]
@thecuf the `0` actually means `Thread::Queue` *is* there (you're checking the exit code of the `perl` command you ran, `0` means success).

So, now I'm really confused...

Maybe the actual problem you are running into is different? Can you dive into the log file?

**Comment by thecuf** [comment]
@boegel  Do you need the config.log file ? I've attached.
[config_log.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/1074237/config_log.txt)

**Comment by thecuf** [comment]
Hi googling on this error I've made an attempt issuing this command

alfredo@LinuxDebianDevelop:~/added_libraries/automake-1.15$ perllibdir=lib ./doc/help2man -S FSF ./t/wrap/aclocal-1.15 > output.1

result is 


Can't load '/usr/local/lib/perl5/5.26.0/i686-linux/auto/Fcntl/Fcntl.so' for module Fcntl: /usr/local/lib/perl5/5.26.0/i686-linux/auto/Fcntl/Fcntl.so: undefined symbol: PL_stack_sp at /usr/local/lib/perl5/5.26.0/XSLoader.pm line 96.
 at /usr/local/lib/perl5/5.26.0/i686-linux/Fcntl.pm line 66.
Compilation failed in require at /usr/local/lib/perl5/5.26.0/i686-linux/POSIX.pm line 17.
BEGIN failed--compilation aborted at /usr/local/lib/perl5/5.26.0/i686-linux/POSIX.pm line 17.
Compilation failed in require at ./doc/help2man line 26.
BEGIN failed--compilation aborted at ./doc/help2man line 26.


May be useful ? I'm pretty new to Linux so I can't manage this info .
regards
Francesco

**Comment by boegel** [comment]
@thecuf The `config.log` isn't that useful, since that's not where the problem is.

Can you try running `make V=1 VERBOSE=1`? That should show the actually commands being run.

Also, which environment are you running into, e.g. which modules do you have loaded (`module list`)?

**Comment by thecuf** [comment]
HI boegel
These are the modules 
root@LinuxDebianDevelop:/home/alfredo# lsmod
Module                  Size  Used by
bnep                   17184  2 
bluetooth             335968  5 bnep
6lowpan_iphc           16548  1 bluetooth
hid_generic            12369  0 
usbhid                 43759  0 
snd_hda_codec_hdmi     44414  1 
snd_hda_codec_realtek    62056  1 
snd_hda_codec_generic    58021  1 snd_hda_codec_realtek
cfg80211              354219  0 
rfkill                 18387  4 cfg80211,bluetooth
binfmt_misc            12733  1 
nfsd                  236959  2 
auth_rpcgss            45765  1 nfsd
oid_registry           12387  1 auth_rpcgss
nfs_acl                12463  1 nfsd
nfs                   168022  0 
lockd                  73443  2 nfs,nfsd
fscache                44782  1 nfs
sunrpc                211375  6 nfs,nfsd,auth_rpcgss,lockd,nfs_acl
x86_pkg_temp_thermal    12839  0 
intel_powerclamp       17006  0 
intel_rapl             17172  0 
coretemp               12708  0 
kvm_intel             133523  0 
kvm                   334522  1 kvm_intel
crc32_pclmul           12809  0 
evdev                  17136  25 
aesni_intel            17934  0 
aes_i586               16647  1 aesni_intel
xts                    12583  1 aesni_intel
lrw                    12645  1 aesni_intel
gf128mul               12834  2 lrw,xts
ablk_helper            12508  1 aesni_intel
cryptd                 14124  1 ablk_helper
serio_raw              12737  0 
pcspkr                 12531  0 
snd_hda_intel          26023  10 
snd_hda_controller     26262  1 snd_hda_intel
snd_hda_codec          93797  5 snd_hda_codec_realtek,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_intel,snd_hda_controller
snd_hwdep              12906  1 snd_hda_codec
shpchp                 30673  0 
snd_soc_rt5640         58146  0 
snd_soc_rl6231         12410  1 snd_soc_rt5640
i915                  766751  7 
snd_soc_core          132308  1 snd_soc_rt5640
snd_compress           17045  1 snd_soc_core
snd_pcm                78128  6 snd_soc_rt5640,snd_soc_core,snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_hda_controller
drm_kms_helper         44450  1 i915
battery                13164  0 
snd_timer              26149  1 snd_pcm
drm                   207686  6 i915,drm_kms_helper
mei_me                 17653  0 
snd                    55101  30 snd_hda_codec_realtek,snd_soc_core,snd_hwdep,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel,snd_compress
regmap_i2c             12695  1 snd_soc_rt5640
mei                    61632  1 mei_me
i2c_algo_bit           12647  1 i915
soundcore              12890  2 snd,snd_hda_codec
video                  17763  1 i915
snd_soc_sst_acpi       12503  0 
acpi_pad               12845  0 
button                 12824  1 i915
processor              27590  0 
fuse                   81592  3 
parport_pc             26004  0 
ppdev                  16686  0 
lp                     12766  0 
parport                35213  3 lp,ppdev,parport_pc
autofs4                34865  2 
ext4                  442557  1 
crc16                  12327  2 ext4,bluetooth
mbcache                17027  1 ext4
jbd2                   72964  1 ext4
sg                     25573  0 
sd_mod                 43684  3 
crc_t10dif             12399  1 sd_mod
crct10dif_generic      12517  1 
crct10dif_common       12340  2 crct10dif_generic,crc_t10dif
ahci                   29134  2 
ehci_pci               12464  0 
xhci_hcd              143252  0 
libahci                22574  1 ahci
ehci_hcd               64933  1 ehci_pci
crc32c_intel           12659  0 
libata                161908  2 ahci,libahci
psmouse                93505  0 
scsi_mod              164132  3 sg,libata,sd_mod
e1000e                192552  0 
alx                    35503  0 
mdio                   12535  1 alx
usbcore               171098  4 ehci_hcd,ehci_pci,usbhid,xhci_hcd
ptp                    17462  1 e1000e
pps_core               17080  1 ptp
usb_common             12408  1 usbcore
thermal                17343  0 
fan                    12601  0 
thermal_sys            27122  6 fan,video,intel_powerclamp,thermal,processor,x86_pkg_temp_thermal
i2c_hid                17210  0 
hid                    81008  3 i2c_hid,hid_generic,usbhid
sdhci_acpi             12714  0 
sdhci                  34721  1 sdhci_acpi
i2c_designware_platform    12573  0 
i2c_designware_core    12701  1 i2c_designware_platform
mmc_core               91803  2 sdhci,sdhci_acpi
i2c_core               36838  8 drm,i915,snd_soc_rt5640,i2c_hid,i2c_designware_platform,regmap_i2c,drm_kms_helper,i2c_algo_bit

and this is the results of make V=1

root@LinuxDebianDevelop:/home/alfredo/added_libraries/automake-1.15# make V=1
rm -f bin/automake bin/automake-t bin/automake-t2 \
  && /bin/mkdir -p bin \
  && in=bin/automake.in && ( sed -e "s,[@]configure_input[@],Generated from $in; do not edit by hand.,g" -e 's,[@]datadir[@],/usr/local/share,g' -e 's,[@]amdir[@],/usr/local/share/automake-1.15/am,g' -e 's,[@]bindir[@],/usr/local/bin,g' -e 's,[@]docdir[@],/usr/local/share/doc/automake,g' -e 's,[@]pkgvdatadir[@],/usr/local/share/automake-1.15,g' -e 's,[@]scriptdir[@],/usr/local/share/automake-1.15,g' -e 's,[@]automake_acdir[@],/usr/local/share/aclocal-1.15,g' -e 's,[@]system_acdir[@],/usr/local/share/aclocal,g' -e 's,[@]am__isrc[@],!!@!!am__isrc!!@!!,g' | /bin/bash ./config.status --file=- | sed -e 's,!!@!!am__isrc!!@!!,@''am__isrc@,g' ) <./$in >bin/automake-t \
  && /usr/local/bin/perl -w ./bin/gen-perl-protos bin/automake-t > bin/automake-t2 \
  && mv -f bin/automake-t2 bin/automake-t \
  && chmod a+x,a-w bin/automake-t && mv -f bin/automake-t bin/automake
rm -f bin/aclocal bin/aclocal-t bin/aclocal-t2 \
  && /bin/mkdir -p bin \
  && in=bin/aclocal.in && ( sed -e "s,[@]configure_input[@],Generated from $in; do not edit by hand.,g" -e 's,[@]datadir[@],/usr/local/share,g' -e 's,[@]amdir[@],/usr/local/share/automake-1.15/am,g' -e 's,[@]bindir[@],/usr/local/bin,g' -e 's,[@]docdir[@],/usr/local/share/doc/automake,g' -e 's,[@]pkgvdatadir[@],/usr/local/share/automake-1.15,g' -e 's,[@]scriptdir[@],/usr/local/share/automake-1.15,g' -e 's,[@]automake_acdir[@],/usr/local/share/aclocal-1.15,g' -e 's,[@]system_acdir[@],/usr/local/share/aclocal,g' -e 's,[@]am__isrc[@],!!@!!am__isrc!!@!!,g' | /bin/bash ./config.status --file=- | sed -e 's,!!@!!am__isrc!!@!!,@''am__isrc@,g' ) <./$in >bin/aclocal-t \
  && /usr/local/bin/perl -w ./bin/gen-perl-protos bin/aclocal-t > bin/aclocal-t2 \
  && mv -f bin/aclocal-t2 bin/aclocal-t \
  && chmod a+x,a-w bin/aclocal-t && mv -f bin/aclocal-t bin/aclocal
rm -f t/ax/shell-no-trail-bslash t/ax/shell-no-trail-bslash-t
in=t/ax/shell-no-trail-bslash.in \
  && /bin/mkdir -p t/ax \
  && ( sed -e "s,[@]configure_input[@],Generated from $in; do not edit by hand.,g" -e 's,[@]datadir[@],/usr/local/share,g' -e 's,[@]amdir[@],/usr/local/share/automake-1.15/am,g' -e 's,[@]bindir[@],/usr/local/bin,g' -e 's,[@]docdir[@],/usr/local/share/doc/automake,g' -e 's,[@]pkgvdatadir[@],/usr/local/share/automake-1.15,g' -e 's,[@]scriptdir[@],/usr/local/share/automake-1.15,g' -e 's,[@]automake_acdir[@],/usr/local/share/aclocal-1.15,g' -e 's,[@]system_acdir[@],/usr/local/share/aclocal,g' -e 's,[@]am__isrc[@],!!@!!am__isrc!!@!!,g' | /bin/bash ./config.status --file=- | sed -e 's,!!@!!am__isrc!!@!!,@''am__isrc@,g' ) <./$in >t/ax/shell-no-trail-bslash-t \
  && chmod a+x t/ax/shell-no-trail-bslash-t
if LC_ALL=C grep '@[a-zA-Z0-9_][a-zA-Z0-9_]*@' t/ax/shell-no-trail-bslash-t; then echo "t/ax/shell-no-trail-bslash contains unexpanded substitution (see lines above)"; exit 1; fi; chmod a-w t/ax/shell-no-trail-bslash-t && mv -f t/ax/shell-no-trail-bslash-t t/ax/shell-no-trail-bslash
rm -f t/ax/cc-no-c-o t/ax/cc-no-c-o-t
in=t/ax/cc-no-c-o.in \
  && /bin/mkdir -p t/ax \
  && ( sed -e "s,[@]configure_input[@],Generated from $in; do not edit by hand.,g" -e 's,[@]datadir[@],/usr/local/share,g' -e 's,[@]amdir[@],/usr/local/share/automake-1.15/am,g' -e 's,[@]bindir[@],/usr/local/bin,g' -e 's,[@]docdir[@],/usr/local/share/doc/automake,g' -e 's,[@]pkgvdatadir[@],/usr/local/share/automake-1.15,g' -e 's,[@]scriptdir[@],/usr/local/share/automake-1.15,g' -e 's,[@]automake_acdir[@],/usr/local/share/aclocal-1.15,g' -e 's,[@]system_acdir[@],/usr/local/share/aclocal,g' -e 's,[@]am__isrc[@],!!@!!am__isrc!!@!!,g' | /bin/bash ./config.status --file=- | sed -e 's,!!@!!am__isrc!!@!!,@''am__isrc@,g' ) <./$in >t/ax/cc-no-c-o-t \
  && chmod a+x t/ax/cc-no-c-o-t
if LC_ALL=C grep '@[a-zA-Z0-9_][a-zA-Z0-9_]*@' t/ax/cc-no-c-o-t; then echo "t/ax/cc-no-c-o contains unexpanded substitution (see lines above)"; exit 1; fi; chmod a-w t/ax/cc-no-c-o-t && mv -f t/ax/cc-no-c-o-t t/ax/cc-no-c-o
rm -f runtest runtest-t
in=t/ax/runtest.in \
  && /bin/mkdir -p t/ax \
  && ( sed -e "s,[@]configure_input[@],Generated from $in; do not edit by hand.,g" -e 's,[@]datadir[@],/usr/local/share,g' -e 's,[@]amdir[@],/usr/local/share/automake-1.15/am,g' -e 's,[@]bindir[@],/usr/local/bin,g' -e 's,[@]docdir[@],/usr/local/share/doc/automake,g' -e 's,[@]pkgvdatadir[@],/usr/local/share/automake-1.15,g' -e 's,[@]scriptdir[@],/usr/local/share/automake-1.15,g' -e 's,[@]automake_acdir[@],/usr/local/share/aclocal-1.15,g' -e 's,[@]system_acdir[@],/usr/local/share/aclocal,g' -e 's,[@]am__isrc[@],!!@!!am__isrc!!@!!,g' | /bin/bash ./config.status --file=- | sed -e 's,!!@!!am__isrc!!@!!,@''am__isrc@,g' ) <./$in >runtest-t \
  && chmod a+x runtest-t
if LC_ALL=C grep '@[a-zA-Z0-9_][a-zA-Z0-9_]*@' runtest-t; then echo "runtest contains unexpanded substitution (see lines above)"; exit 1; fi; chmod a-w runtest-t && mv -f runtest-t runtest
: \
  && /bin/mkdir -p doc \
  && f=`echo doc/aclocal.1 | sed 's|.*/||; s|\.1$||; s,x,x,'` \
  && echo ".so man1/$f-1.15.1" > doc/aclocal.1
: \
  && /bin/mkdir -p doc \
  && f=`echo doc/automake.1 | sed 's|.*/||; s|\.1$||; s,x,x,'` \
  && echo ".so man1/$f-1.15.1" > doc/automake.1
rm -f lib/Automake/Config.pm lib/Automake/Config.pm-t
/bin/mkdir -p lib/Automake
in=Config.in \
  && ( sed -e "s,[@]configure_input[@],Generated from $in; do not edit by hand.,g" -e 's,[@]datadir[@],/usr/local/share,g' -e 's,[@]amdir[@],/usr/local/share/automake-1.15/am,g' -e 's,[@]bindir[@],/usr/local/bin,g' -e 's,[@]docdir[@],/usr/local/share/doc/automake,g' -e 's,[@]pkgvdatadir[@],/usr/local/share/automake-1.15,g' -e 's,[@]scriptdir[@],/usr/local/share/automake-1.15,g' -e 's,[@]automake_acdir[@],/usr/local/share/aclocal-1.15,g' -e 's,[@]system_acdir[@],/usr/local/share/aclocal,g' -e 's,[@]am__isrc[@],!!@!!am__isrc!!@!!,g' | /bin/bash ./config.status --file=- | sed -e 's,!!@!!am__isrc!!@!!,@''am__isrc@,g' ) <./lib/Automake/Config.in >lib/Automake/Config.pm-t
if LC_ALL=C grep '@[a-zA-Z0-9_][a-zA-Z0-9_]*@' lib/Automake/Config.pm-t; then echo "lib/Automake/Config.pm contains unexpanded substitution (see lines above)"; exit 1; fi; chmod a-w lib/Automake/Config.pm-t && mv -f lib/Automake/Config.pm-t lib/Automake/Config.pm
: && /bin/mkdir -p doc && { PATH='/home/alfredo/added_libraries/automake-1.15/t/wrap:'$PATH && export PATH; } && /usr/local/bin/perl ./doc/help2man --output=doc/aclocal-1.15.1 aclocal-1.15
: && /bin/mkdir -p doc && { PATH='/home/alfredo/added_libraries/automake-1.15/t/wrap:'$PATH && export PATH; } && /usr/local/bin/perl ./doc/help2man --output=doc/automake-1.15.1 automake-1.15
help2man: can't get `--help' info from automake-1.15
Try `--no-discard-stderr' if option outputs to stderr
Makefile:3687: recipe for target 'doc/automake-1.15.1' failed
make: *** [doc/automake-1.15.1] Error 255

regards

**Comment by boegel** [comment]
I meant the output of `module list` (i.e. loaded environment modules), not `lsmod` (kernel modules), but I guess you're just trying to get this built manually?

I'm not sure what's going wrong, but I think the actual problem is being hidden, as the `Try '--no-discard-stderr' if option outputs to stderr` suggests.

I'm not sure where you need to use `--no-discard-stderr` though, I guess you have add that to where `help2man` is being called in the `Makefile`?

**Comment by thecuf** [comment]
Hi boegel
further step forward but I've another problem. If I issue "module list" command  gives me "command not found".  I modified the makefile and it seems that now compile and install.  But when I gives the command automake --version the result is:

root@LinuxDebianDevelop:/home/alfredo/added_libraries/automake-1.15# automake --version
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/local/bin/automake line 3936.

the same result if I attempt to compile vlc contrib modules (this is why I've installed automake 1.1.5).
regards

**Comment by boegel** [comment]
@thecuf `module` is not a standard tool, but it's common on HPC systems where EasyBuild is typically being used, so don't worry about that too much

I have no idea about the regex issue with `automake`, I'm sorry.

**Comment by queshaw** [comment]
According to https://unix.stackexchange.com/questions/238539/automake-error-unescaped-left-brace-in-regex-is-deprecated perl changed the warning about unescaped left brace to be an error. So, I guess, for now, a requirement for building automake is to use perl version not later than 5.22?

I was having nearly every test fail until using using perl 5.20.3 instead of 5.26. This also avoided the help2man: can't get `--help' info from automake-1.15 error.

**Comment by boegel** [comment]
@queshaw That makes sense...

The only way around that would be if we include a sufficiently recent version of Perl ourselves as a build dependency to `automake`...

**Comment by andreas-h** [comment]
I'm running into the same error on my Debian Testing system:

    $ perl --version                      
    
    This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-gnu-thread-multi
    (with 53 registered patches, see perl -V for more detail)
    
    Copyright 1987-2017, Larry Wall
    
    Perl may be copied only under the terms of either the Artistic License or the
    GNU General Public License, which may be found in the Perl 5 source kit.
    
    Complete documentation for Perl, including FAQ lists, should be found on
    this system using "man perl" or "perldoc perl".  If you have access to the
    Internet, point your browser at http://www.perl.org/, the Perl Home Page.

Automake doesn't produce the error mentioned previously:

    $ automake --version
    automake (GNU automake) 1.15.1
    Copyright (C) 2017 Free Software Foundation, Inc.
    License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Written by Tom Tromey <tromey@redhat.com>
           and Alexandre Duret-Lutz <adl@gnu.org>.

And also I can use `Thread::Queue`:

    $ perl -e 'use Thread::Queue'; echo $?
    0

Still:

    == 2017-08-18 15:14:35,929 build_log.py:156 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/3.3.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/exceptions.py:124 in __init__): cmd " make -j 4 " exited with exitcode
      GEN      bin/automake
      GEN      bin/aclocal
      GEN      t/ax/shell-no-trail-bslash
      GEN      t/ax/cc-no-c-o
      GEN      runtest
      GEN      doc/aclocal.1
      GEN      doc/automake.1
      GEN      lib/Automake/Config.pm
      GEN      t/ax/test-defs.sh
      GEN      doc/automake-1.15.1
      GEN      doc/aclocal-1.15.1
    help2man: can't get `--help' info from automake-1.15
    Try `--no-discard-stderr' if option outputs to stderr
    Makefile:3687: recipe for target 'doc/automake-1.15.1' failed
    make: *** [doc/automake-1.15.1] Error 255

Any ideas?

**Comment by zao** [comment]
On Ubuntu 18.04 alpha I compared the failing Automake 1.15 build with a 1.15.1.
The core difference is in `bin/automake.in` where as alluded by @queshaw there is an unescaped `{` that trips Perl up. Version 1.15.1 simply changes it into a literal `[{]` silencing the warning.
An `Automake-1.15.eb` with that as a patch builds fine.
