### PR TITLE
Fix building flex 2.6.4 on glibc 2.26+

### PR DESCRIPTION
**Pull request by crubb**
flex 2.6.4 fails to build with glibc 2.26+, since `reallocarray()` needs to be enabled, otherwise a segfault will occur during building, with the following errors during compiling:

```
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR=\"/software/easybuild/software/flex/2.6.4/share/locale\"   -g -O2 -MT stage1flex-yylex.o -MD -MP -MF .deps/stage1flex-yylex.Tpo -c -o stage1flex-yylex.o `test -f 'yylex.c' || echo './'`yylex.c
misc.c: In function ‘allocate_array’:
misc.c:147:8: warning: implicit declaration of function ‘reallocarray’; did you mean ‘reallocate_array’? [-Wimplicit-function-declaration]
  mem = reallocarray(NULL, (size_t) size, element_size);
        ^~~~~~~~~~~~
        reallocate_array
misc.c:147:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  mem = reallocarray(NULL, (size_t) size, element_size);
      ^
misc.c: In function ‘reallocate_array’:
misc.c:664:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  new_array = reallocarray(array, (size_t) size, element_size);
            ^
misc.c: In function ‘allocate_array’:
misc.c:147:8: warning: implicit declaration of function ‘reallocarray’; did you mean ‘reallocate_array’? [-Wimplicit-function-declaration]
  mem = reallocarray(NULL, (size_t) size, element_size);
        ^~~~~~~~~~~~
        reallocate_array
misc.c:147:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  mem = reallocarray(NULL, (size_t) size, element_size);
      ^
misc.c: In function ‘reallocate_array’:
misc.c:664:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  new_array = reallocarray(array, (size_t) size, element_size);
            ^
```

Fix is taken from https://github.com/westes/flex/commit/c5a26b1 (issue and discussion: https://github.com/westes/flex/issues/241).

In the process, `Automake-1.15` needed to be added to the `flex-2.6.4` and `flex-2.6.4-GCCcore-7.3.0` easyblocks, which caused a dependency loop, until `binutils-2.30` was set to use the same binutils version that was used when building GCC toolchain in `Autoconf-2.69-GCCcore-7.3.0`.

The `Automake-1.15s-fix-brace.patch` was also added to `Automake-1.15.eb` (already in the other Automake EBs).

`Bison` and `help2man` dependencies were updated in the process.

I hope this is not too much squashed into a single PR.

### CODE REVIEW

**Comment by akesandgren** [comment]
There is a much simpler fix in PR #5792

File: easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.3.0.eb [hunk 1]
```diff
@@ -14,11 +14,16 @@ toolchainopts = {'pic': True}
...
+checksums = [
+    'e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995',  # flex-2.6.4.tar.gz
+    '2975201c6ec3687219cb1b7f85f04aee227ea67f0491ba16d50f0384a8e02630',  # flex-2.6.4_system_extension.patch
+]
 
 builddependencies = [
-    ('Bison', '3.0.4'),
-    ('help2man', '1.47.4'),
+    ('Bison', '3.0.5'),
+    ('help2man', '1.47.6'),
```
Comment (boegel) [inline easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.3.0.eb]: @crubb bumping versions in existing easyconfigs is not going to work out, especially for low-level stuff like `flex`...

**Comment by crubb** [comment]
Easier is always better.
