### PR TITLE
switch to Rust 1.60.0 build dependency for bamtofastq, since build of  fails with Rust 1.52.1 (E0658)

### PR DESCRIPTION
**Pull request by pberthier**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by pberthier** [comment]
Test report by @pberthier
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
softdev.binf.unibe.ch - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, Python 3.6.8
See https://gist.github.com/db975c82458378acd0b5389e17a68d46 for a full test report.

**Comment by boegel** [comment]
@pberthier Do you have some more details here, the exact error that you're running into with Rust 1.52.1?

Because it definitely used to work, see #14391

**Comment by pberthier** [comment]
Does the build logfile helps?
[easybuild-bamtofastq-1.4.0-20220609.121200.kBTnh.log](https://github.com/easybuilders/easybuild-easyconfigs/files/8869399/easybuild-bamtofastq-1.4.0-20220609.121200.kBTnh.log)

**Comment by boegel** [comment]
First error produced by Rust compiler:

```
error[E0658]: arbitrary expressions in key-value attributes are unstable
   --> /home/softdev/.cargo/registry/src/github.com-1ecc6299db9ec823/libz-sys-1.1.8/src/lib.rs:115:19
    |
115 |     #[link_name = zng_prefix!(adler32)]
    |                   ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
    = help: add `#![feature(extended_key_value_attributes)]` to the crate attributes to enable
```

That looks very similar to the problem that led me to use a more recent Rust version for `tokenizers` in #15587...

This is probably a result of pulling in Rust packages during the installation of Rust, it looks like we may be pulling in package versions that are not actually compatible with Rust 1.52.1 (while we weren't before).

@zao Any thoughts on this, since you're a bit more familiar with the Rust ecosystem?

**Comment by boegel** [comment]
Actually, it's probably because whatever Rust packages are required for `bamtofastq` are being downloaded on the fly during the installation of `bamtofastq` itself, without proper version locking...

So we're now pulling in `libz-sys-1.1.8`, which requires a Rust version newer than 1.52.1, while before we were pulling down an older version of `libz-sys` that worked fine with Rust 1.52.1.

So bumping the Rust version we're using as a build dep to something more recent is a short term solution, but we're bound to run into the same problem again later, and we need to properly fix this by making sure we install the same dependency versions...

**Comment by boegel** [comment]
@zao Any thoughts on this (since you're more familiar with the Rust ecosystem)?

**Comment by verdurin** [comment]
Ping @zao @boegel

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3138.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/6c2a90646eb12ee8b27e6e8491d960bc for a full test report.

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
Going in, thanks @pberthier!
