### PR TITLE
{devel}[GCCcore/8.3.0] Bazel v0.26.1

### PR DESCRIPTION
**Pull request by Flamefire**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by boegel** [comment]
(close/re-open to wake up Travis/GitHub Actions to run the tests...)

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3302.joltik.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, Python 2.7.5
See https://gist.github.com/6b540c6bb3a5ff3daa9bdf9fbaceba9f for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3209.victini.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/5761a2a0d987e29d38b2326ea85ebd81 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/28b2734a806448cf4c31f31eb7a1b532 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2465.golett.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/c259151ef56bfc7e1bcec267526c2fa8 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @Flamefire!

**Comment by JackPerdue** [comment]
On CentOS6 (with python-2.6.6), I had to add Python 2.7 as a builddep.

builddependencies = [('binutils', '2.32'), ('Python', '2.7.16')]

otherwise it failed to build with:

Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "bazel-out/host/bin/src/create_embedded_tools/__main__.py", line 252, in <module>
  File "bazel-out/host/bin/src/create_embedded_tools/__main__.py", line 181, in Main
  File "bazel-out/host/bin/src/create_embedded_tools/__main__.py", line 132, in CreateModuleSpace
  File "bazel-out/host/bin/src/create_embedded_tools/__main__.py", line 116, in ExtractZip
AttributeError: ZipFile instance has no attribute '__exit__'
Target //src:bazel_nojdk failed to build

**Comment by Flamefire** [comment]
Ouch, there is an OS with Python 2.6? Isn't easybuild itself running on 2.7?

According to https://docs.bazel.build/versions/master/install-compile-source.html bazel supports Python 2&3 so I'd rather install Python 3.7.4 as builddependency

**Comment by boegel** [comment]
@Flamefire Python 2.6 is the system Python in CentOS 6. We still support running EasyBuild on top of Python 2.6, but not for much longer (we're deprecating that support for the next EasyBuild release, see https://github.com/easybuilders/easybuild-framework/pull/3076).

@JackPerdue Please open an issue on this, it's impossible to keep track of things to do in merged PRs.

**Comment by JackPerdue** [comment]
Done. https://github.com/easybuilders/easybuild-easyconfigs/issues/9295
