### PR TITLE
{lib}[GCCcore/13.3.0,gfbf/2024a] tensorstore v0.1.72, BLAKE3-C v1.6.1

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)

### CODE REVIEW

File: easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+source_urls = ['https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/']
+sources = ['%(version)s.tar.gz']
+checksums = ['1f2fbd93790694f1ad66eef26e23c42260a1916927184d78d8395ff1a512d285']
+
+builddependencies = [
+    ('CMake', '3.29.3'),
+    ('binutils', '2.42'),
+]
+dependencies = []
```
Comment (akesandgren) [inline easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb:27]: If there are no dependencies then don't specify an empty list. Drop it.

File: easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+postinstallcmds = ['cp *.%s %%(installdir)s/lib' % SHLIB_EXT]
+start_dir = 'c'
+configopts = '-DBUILD_SHARED_LIBS=ON '
```
Comment (akesandgren) [inline easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb:30]: Don't do this, use the CMakeMake option: build_shared_libs = True instead

File: easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+configopts += '-DCMAKE_INSTALL_LIBDIR=lib '
```
Comment (akesandgren) [inline easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb:31]: This is the default in the CMakeMake easyblock, drop it.

File: easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+
+sanity_check_paths = {
+    'files': ['lib/libblake3.%s' % SHLIB_EXT],
+    'dirs': ['include/', 'lib/'],
```
Comment (akesandgren) [inline easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb:35]: Drop the /-suffixes on the dir names, and lib is not needed since you have that through files.

File: easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+
+toolchain = {'name': 'GCCcore', 'version': '13.3.0'}
+
+source_urls = ['https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/']
+sources = ['%(version)s.tar.gz']
+checksums = ['1f2fbd93790694f1ad66eef26e23c42260a1916927184d78d8395ff1a512d285']
+
+builddependencies = [
+    ('CMake', '3.29.3'),
+    ('binutils', '2.42'),
```
Comment (akesandgren) [inline easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb:25]: Swap order on these two, binutils should come first.

File: easybuild/easyconfigs/l/libavif/libavif-1.2.0-GCCcore-13.3.0.eb [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+toolchain = {'name': 'GCCcore', 'version': '13.3.0'}
+
+source_urls = ['https://github.com/AOMediaCodec/libavif/archive/']
+sources = ['v%(version)s.tar.gz']
+checksums = ['2182f4900d1a9617cee89746922a58dd825f2a3547f23907b8d78dc3685f7d8c']
+
+builddependencies = [
+    ('CMake', '3.29.3'),
+    ('binutils', '2.42'),
```
Comment (akesandgren) [inline easybuild/easyconfigs/l/libavif/libavif-1.2.0-GCCcore-13.3.0.eb:22]: Swap order here

File: easybuild/easyconfigs/l/libavif/libavif-1.2.0-GCCcore-13.3.0.eb [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+    ('NASM', '2.16.03'),
+    ('Meson', '1.4.0'),
+    ('Ninja', '1.12.1'),
+    ('Rust', '1.78.0'),
+    ('pkgconf', '2.2.0'),
+]
+dependencies = [
```
Comment (akesandgren) [inline easybuild/easyconfigs/l/libavif/libavif-1.2.0-GCCcore-13.3.0.eb:29]: Add blank line before dependencies for style

File: easybuild/easyconfigs/l/libyuv/libyuv-20250227-GCCcore-13.3.0.eb [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+source_urls = ['https://github.com/lemenkov/libyuv/archive/']
+sources = [{
+    "download_filename": "%s.tar.gz" % local_commit,
+    "filename": SOURCE_TAR_GZ,
+}]
+checksums = ['b509e836fde118b70f5f65b0c6835c724b37b63d4a5d52c2b49f76944645e948']
+
+builddependencies = [
+    ('CMake', '3.29.3'),
+    ('binutils', '2.42'),
```
Comment (akesandgren) [inline easybuild/easyconfigs/l/libyuv/libyuv-20250227-GCCcore-13.3.0.eb:21]: Swap order

File: easybuild/easyconfigs/l/libyuv/libyuv-20250227-GCCcore-13.3.0.eb [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+]
+
+sanity_check_paths = {
+    'files': ['bin/yuvconvert', f'lib/{name}.so', f'lib/{name}.a', f'include/{name}.h'],
```
Comment (akesandgren) [inline easybuild/easyconfigs/l/libyuv/libyuv-20250227-GCCcore-13.3.0.eb:25]: This should be "lib/%%(name)s.%s" % SHLIB_EXT" and lib/%(name)s.a" etc to follow the style of EB

File: easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb [hunk 10]
```diff
@@ -0,0 +1,401 @@
...
+name = 'tensorstore'
+version = '0.1.72'
+
+homepage = 'https://github.com/google/tensorstore'
+description = """TensorStore is an open-source C++ and Python software library designed for      
+storage and manipulation of large multi-dimensional arrays."""
+
+toolchain = {'name': 'gfbf', 'version': '2024a'}
+
+use_pip = True
```
Comment (akesandgren) [inline easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb:13]: Drop this, it's the default since EB 5 and will cause a complaint in the CI

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 15 out of 15 (7 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/149f6fd2b933e0df753e3b3967dd5473 for a full test report.

File: easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb [hunk 11]
```diff
@@ -0,0 +1,401 @@
...
+    ],
+    'sources': _sources_nameminversion,
+}
+#
+components = [
+    ('aws-c-auth', '0.8.4', {
+        'sources': [{
+            'download_filename': 'v%(version)s.tar.gz',
+            'filename': '%(name)s-%(version)s.tar.gz',
+            'extract_cmd': _extract_cmd + 'v0.8.4.tar.gz',
```
Comment (akesandgren) [inline easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb:142]: If it works (I'm not 100% sure) you should use _extract_cmd + 'v%(version)s.tar.gz' here and on all the corresponding lines below.

File: easybuild/easyconfigs/t/tinyxml2/tinyxml2-10.0.0-GCCcore-13.3.0.eb [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+
+github_account = 'leethomason'
+source_urls = [GITHUB_SOURCE]
+sources = ['%(version)s.tar.gz']
+patches = []
+checksums = ['3bdf15128ba16686e69bce256cc468e76c7b94ff2c7f391cc5ec09e40bff3839']
+
+builddependencies = [
+    ('CMake', '3.29.3'),
+    ('binutils', '2.42'),
```
Comment (akesandgren) [inline easybuild/easyconfigs/t/tinyxml2/tinyxml2-10.0.0-GCCcore-13.3.0.eb:21]: Swap order

**Comment by akesandgren** [comment]
See Static analysis: there are a couple of trailing white spaces that need to be removed

**Comment by ThomasHoffmann77** [comment]
> See Static analysis: there are a couple of trailing white spaces that need to be removed
What's the problem with them? These white spaces belong to the description.

File: easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb [hunk 13]
```diff
@@ -0,0 +1,399 @@
...
+        ],
+        'preinstallopts': _preinstall_opts,
+        'checksums': [
+            {'tensorstore-0.1.72.tar.gz': '763d7f6898711783f199c8226a9c0b259546f5c6d9b4dc0ad3c9e39627060022'},
+            {'tensorstore-0.1.69_bazelisk.patch': 'f7bb3dc7265597c6ae999df8b17d6e7300c0c0ce307579909a2af8738d78026f'},
+        ],
+    }),
+]
+
+sanity_pip_check = True
```
Comment (akesandgren) [inline easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb:397]: As of EB 5 this should be dropped since it is now the default.

**Review by akesandgren — CHANGES_REQUESTED** [review]

**Comment by akesandgren** [comment]
And some trailing whitespace:
```
./easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb:11:80: W291 trailing whitespace
./easybuild/easyconfigs/b/BLAKE3-C/BLAKE3-C-1.6.1-GCCcore-13.3.0.eb:13:76: W291 trailing whitespace
./easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb:8:92: W291 trailing whitespace
./easybuild/easyconfigs/t/tinyxml2/tinyxml2-10.0.0-GCCcore-13.3.0.eb:8:93: W291 trailing whitespace
```

**Comment by akesandgren** [comment]
Test report by @akesandgren
**FAILED**
Build succeeded for 6 out of 7 (6 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/8c04a8aee332cf327773b96194638a7c for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3

**Comment by branfosj** [comment]
```
easyblock.py:2984 DEBUG Trying to execute True as a command for running unit tests...
build_log.py:226 ERROR EasyBuild encountered an error (at easybuild/base/exceptions.py:126 in __init__): Unknown command type ('<class 'bool'>'): True (at easybuild/tools/run.py:399 in to_cmd_str)
```

Broken by the change in https://github.com/easybuilders/easybuild-easyblocks/pull/3748

File: easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb [hunk 14]
```diff
@@ -0,0 +1,397 @@
...
+    'com_github_cares_cares',
+    'libwebp',
+    'nasm',
+    'com_google_snappy',
+    'tinyxml2',
+    'org_blosc_cblosc',
+    'blake3'
+]
+
+# Generate list of includ paths and link path for syslibs to be passed to Bazel as --copt and --linkopt
```
Comment (akesandgren) [inline easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb]: While we're waiting for a solution to the test problem, can you fix the typo here? "includ" -> include

File: easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb [hunk 15]
```diff
@@ -0,0 +1,397 @@
...
+        "https://storage.googleapis.com/tensorstore-bazel-mirror/github.com/google/%(name)s/archive",
+        'https://storage.googleapis.com/tensorstore-bazel-mirror/github.com/google/%(name)s/releases/download/' +
+        '%(version)s/',
+        'https://storage.googleapis.com/tensorstore-bazel-mirror/sourceforge.net/projects/%(name)s/files/%(name)s/' +
+        '%(version)s',
+        'https://github.com/bazelbuild/%(name)s/releases/download/%(version)s/',
+        'https://storage.googleapis.com/tensorstore-bazel-mirror/github.com/awslabs/%(name)s/archive/',
+        'https://storage.googleapis.com/tensorstore-bazel-mirror/github.com/aws/%(name)s/archive/'
+    ],
+    'sources': _sources_nameminversion,
```
Comment (akesandgren) [inline easybuild/easyconfigs/t/tensorstore/tensorstore-0.1.72-gfbf-2024a.eb:133]: As a workaround it was suggested to add
'runtest': None,
here.
Could you please do that and I'll rerun the test build.

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/096272915edcbe226bf50f307845156e for a full test report.

**Comment by akesandgren** [comment]
Going in, thanks @ThomasHoffmann77!

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="tensorstore-0.1.72-gfbf-2024a.eb"
