### PR TITLE
ENT-v1.0.2

### PR DESCRIPTION
**Pull request by rtripath89**
Submitting an Easyconfig for ENT v1.0.2

### CODE REVIEW

File: easybuild/easyconfigs/e/ENT/ENT-1.0.2.eb [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+source_urls = ['http://dna.engr.uconn.edu/~software/ent/']
+sources = ['ent_%(version)s.tar.gz']
+
+install_cmd = "tar xvzf ent_%(version)s.tar.gz &&"
+install_cmd += "cd %(builddir)s/ent_%(version)s &&"
+install_cmd += "make all &&"
+install_cmd += "cp -a %(builddir)s/ent_%(version)s/* %(installdir)s"
+
+dependencies = [
+     ('GCC', '4.7.2'),
```
Comment (boegel) [inline easybuild/easyconfigs/e/ENT/ENT-1.0.2.eb]: @rtripath89 why does this need `GCC` as a dependency, especially such an old version?

Wouldn't it be better to use GCC as a toolchain then rather than `dummy` to make this more explicit (e.g. in the module name)?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node2159.delcatty.os - Linux SL 6.7, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/18fcabd46cb1ebc88b86724dc348c11f for a full test report.

**Comment by boegel** [comment]
@rtripath89 doesn't work for me, I'm running into problems like:

````
ain.cc:187: error: ‘strlen’ was not declared in this scope
```

**Comment by rtripath89** [comment]
Strange...I tested it on an old system with older gcc and it worked fine, but when I tested it on newer GCC it's throwing up the error that you mentioned. One method, how I was able to get it to build with GCC/v4.7.2, was when I changed the main.cc (after untarring the source file) to include string.h instead of string and tar'd up the changed folder, and put it in the sources. I don't know how to automate this in an Easyconfig. Do you think adding comments for this would suffice, or if their is another method?

**Comment by boegel** [comment]
@rtripath89 the proper way would be creating a patch file, something like this:

```
tar xfvz ent_1.0.2.tar.gz
cp -a ent-1.0.2 ent-1.0.2.orig
vim ent-1.0.2/main.cc  # change string to string.h
diff -ru ent-1.0.2.orig ent-1.0.2 > ent-1.0.2_fix-string-include.patch
```

and than add this to the easyconfig:

```python
patches = ['ent-%(version)s_fix-string-include.patch']
```

and include the patch file in this PR as well

you should also add a short description to the patch on top (any lines above the first `---` line are comments), and specify yourself as the author of the patch

File: easybuild/easyconfigs/e/ENT/ENT-1.0.2.eb (hunk 1 above)
Comment (boegel) [inline easybuild/easyconfigs/e/ENT/ENT-1.0.2.eb]: @rtripath89 This should be taken care of before we can merge this PR...

File: easybuild/easyconfigs/e/ENT/ent_1.0.2_fix-string-include.patch [hunk 2]
```diff
@@ -0,0 +1,11 @@
+diff -ru ent_1.0.2.orig/main.cc ent_1.0.2/main.cc
```
Comment (boegel) [inline easybuild/easyconfigs/e/ENT/ent_1.0.2_fix-string-include.patch]: @rtripath89 please include a brief description + authorship on top

File: easybuild/easyconfigs/e/ENT/ENT-1.0.2.eb [hunk 3]
```diff
@@ -0,0 +1,37 @@
+# This file is an EasyBuild reciPY as per https://github.com/hpcugent/easybuild
+# Author: Ravi Tripathi
+# Email: ravi89@uab.edu
+
+easyblock = "Binary"
```
Comment (boegel) [inline easybuild/easyconfigs/e/ENT/ENT-1.0.2.eb]: @rtripath89 You'll want to use `BinariesTarball` instead, since `Binary` doesn't unpack the `sources`...

Did you test this easyconfig?

**Comment by migueldiascosta** [comment]
@rtripath89, this PR is being closed for the following reason(s): no activity for > 1 year.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer
