### PR TITLE
{data}[intel/2018a] bagit v1.6.4 + BDBag v1.4.1 w/ Python 2.7.14

### PR DESCRIPTION
**Pull request by tovrstra**
Works for me. I managed to create a simple bagit archive with the `bdbag` command after locally installing these configs.

### CODE REVIEW

**Comment by boegel** [comment]
@tovrstra It would be cleaner to collapse these two easyconfigs into a single easyconfig that uses the `Bundle` easyblock and installs all required packages in one directory, see for example https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-2.7.14.eb .

And while you're at it, please also add `exts_download_dep_fail = True` to avoid that additional Python packages are downloaded during the installation (as is the case with `tzlocal` now as dependency for `BDBag`).

**Comment by boegel** [comment]
@tovrstra Please let us know if you're up for making the requested changes.

**Comment by tovrstra** [comment]
Sorry for the delay (exams). I'll give it a try.

**Comment by tovrstra** [comment]
@boegel I've put all three in a bundle, with checksums this time. Still, sanity checks fail and I have no clue why:

```
failing sanity check for 'tzlocal' extension: command "/apps/gent/CO7/haswell-ib/software/Python/2.7.14-intel-2018a/bin/python -c "import tzlocal"" fa
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tzlocal
failing sanity check for 'bagit' extension: command "/apps/gent/CO7/haswell-ib/software/Python/2.7.14-intel-2018a/bin/python -c "import bagit"" failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named bagit
failing sanity check for 'BDBag' extension: command "/apps/gent/CO7/haswell-ib/software/Python/2.7.14-intel-2018a/bin/python -c "import bdbag"" failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named bdbag (at easybuild/framework/easyblock.py:2288 in _sanity_check_step)
```

Manual inspection of the files indicates that all got installed properly. with the three packages present as egg files.

**Comment by boegel** [comment]
@tovrstra That's because you need to extend `$PYTHONPATH` yourself when using `Bundle`, see for example https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-3.6.4.eb#L53 .

Please also enable `full_sanity_check`, see https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-3.6.4.eb#L43

**Comment by tovrstra** [comment]
Done. Also note that I could not get this to work with Python 3.6.4. In that case, I get the following error:

```
== 2018-08-24 11:25:37,604 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " /apps/gent/CO7/haswell-ib/software/Python/3.6.4-intel-2018a/bin/python setup.py build " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    long_description=open('README.rst', 'rt').read() + '\n\n' + open('CHANGES.txt', 'rt').read(),
  File "/apps/gent/CO7/haswell-ib/software/Python/3.6.4-intel-2018a/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2873: ordinal not in range(128)
 (at easybuild/tools/run.py:501 in parse_cmd_output)
```

It must be related to the presence of a unicode characters in the `CHANGES.txt` file of tzlocal.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2448.golett.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/2602c2093390dce7807f34908fe5494e for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3111.skitty.os - Linux centos linux 7.4.1708, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/67c9dd303feaeae45615e4e68d319d45 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2117.delcatty.os - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/880d0793fb1db2c88547b22ff1658491 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @tovrstra!
