### PR TITLE
add patch to M4 v1.4.20 to allow building with glibc v2.43

### LINKED ISSUE #26249: M4 v1.20.0 fails to build with recent glibc (v2.43)
M4 v1.20.0, used in 2025a, 2025b and 2026.1, fails to build with a very recent glibc (e.g., v2.43). 
A build of `M4-1.4.20.eb` fails with:

```
In file included from /usr/include/features.h:540,
                 from /usr/include/errno.h:25,
                 from openat-priv.h:23,
                 from openat-proc.c:22:
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
In file included from /usr/include/features.h:540,
                 from ./wchar.h:69,
                 from btowc.c:21:
./string.h:777:20: error: expected identifier or '(' before '_Generic'
  777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
      |                    ^~~~~~
./wchar.h:838:23: error: expected identifier or '(' before '_Generic'
  838 | _GL_EXTERN_C wchar_t *wmemchr (const wchar_t *__s, wchar_t __wc, size_t __n)
      |                       ^~~~~~~
In file included from /usr/include/features.h:540,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/string.h:26,
                 from ./string.h:41,
                 from basename-lgpl.c:24:
./string.h:777:20: error: expected identifier or '(' before '_Generic'
  777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
      |                    ^~~~~~
In file included from /usr/include/features.h:540,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:26,
                 from ./stdlib.h:51,
                 from gl_avltree_oset.c:23:
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
make[3]: *** [Makefile:4156: libm4_a-basename-lgpl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:4142: libm4_a-gl_avltree_oset.o] Error 1
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
./string.h:777:20: error: expected identifier or '(' before '_Generic'
  777 | _GL_EXTERN_C void *memchr (const void *__s, int __c, size_t __n)
      |                    ^~~~~~
make[3]: *** [Makefile:4198: libm4_a-btowc.o] Error 1
In file included from /usr/include/features.h:540,
                 from /usr/include/sys/types.h:25,
                 from ./sys/types.h:46,
                 from ./signal.h:49,
                 from asyncsafe-spin.h:43,
                 from asyncsafe-spin.c:22:
./stdlib.h:827:20: error: expected identifier or '(' before '_Generic'
  827 | _GL_EXTERN_C void *bsearch (const void *__key,
      |                    ^~~~~~~
make[3]: *** [Makefile:4128: libm4_a-openat-proc.o] Error 1
make[3]: *** [Makefile:4114: libm4_a-asyncsafe-spin.o] Error 1
```

The issue is resolved with M4 v1.4.21. See also #26247. However, this blocks users from recent glibc versions from building all currently available toolchains.

We might be able to come up with a patch, but diffing both versions, it looks like most of the changes were pulled in from updating the `gnulib` submodule. Hence, we'd need to port these changes manually.

Simply changing the C standard is not sufficient.

### PR DESCRIPTION
**Pull request by Thyre**
(created using `eb --new-pr`)

Closes #26249

### CODE REVIEW

**Comment by Thyre** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="--installpath /tmp/$USER/ecpr-26255"

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 3 out of 3 (total: 2 mins 37 secs) (3 easyconfigs in total)
Linux - Linux Arch Linux UNKNOWN, x86_64, AMD Ryzen 7 7800X3D 8-Core Processor (zen4), 1 x AMD Navi 48 [Radeon RX 9070/9070 XT/9070 GRE] (device id: 0x7550, gfx: gfx1201, driver: Linuxversion7.0.11-arch1-1(linux@archlinux)(gcc(GCC)16.1.120260430,GNUld(GNUBinutils)2.46.0)#1SMPPREEMPT_DYNAMICTue,02Jun202618:26:58+0000), 1 x AMD Raphael (device id: 0x164e, gfx: gfx1036, driver: Linuxversion7.0.11-arch1-1(linux@archlinux)(gcc(GCC)16.1.120260430,GNUld(GNUBinutils)2.46.0)#1SMPPREEMPT_DYNAMICTue,02Jun202618:26:58+0000), Python 3.14.5
See https://gist.github.com/Thyre/1f36198071049d53701305ed4d6f6625 for a full test report.

**Comment by Thyre** [comment]
Test report by @Thyre
**SUCCESS**
Build succeeded for 3 out of 3 (total: 5 mins 13 secs) (3 easyconfigs in total)
ZAM054 - Linux Zorin OS 18, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P (skylake), 1 x NVIDIA NVIDIA GeForce MX550, 595.71.05, Python 3.12.3
See https://gist.github.com/Thyre/ae742e9e9d446c898a27155aade39f25 for a full test report.

**Review by Micket — APPROVED** [review]
lgtm
