### ISSUE TITLE
error building Pillow when LibTIFF has been built with --enable-ld-version-script configure option on Centos6 

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-easyconfigs#6953]
specifically, the change introduced in #5945 breaks building Pillow/5.0.0-intel-2018a-Python-3.6.4 (on Centos 6, if that's relevant)

(found in a failed test report for #6947, building LibTIFF without that option fixed it)

**Comment by migueldiascosta** [comment]
the error when building Pillow is
```
/opt/apps/util/easybuild/software/LibTIFF/4.0.9-GCCcore-6.4.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `__bss_start'
/opt/apps/util/easybuild/software/LibTIFF/4.0.9-GCCcore-6.4.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `_end'
/opt/apps/util/easybuild/software/LibTIFF/4.0.9-GCCcore-6.4.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `_edata'
```

**Comment by boegel** [comment]
@migueldiascosta Building `Pillow` on top of a `LibTIFF` that was configured with `--enable-ld-version-script` works fine for me (and many others I guess, or we would have heard about this issue already).

So, it seems like this could be specific to CentOS 6...

**Comment by schiotz** [comment]
I see the same problem, but only when building Pillow with the Intel compiler, not when building with the foss compiler.  This is with CentOS 7.4.

**Comment by boegel** [comment]
This was also discussed on the mailing list, see https://lists.ugent.be/wws/arc/easybuild/2018-10/msg00056.html for the thread started by @schiotz .

I'm still a bit puzzled why I'm not seeing the problem that @schiotz was seeing, since I was also building `LibTIFF` with `GCCcore` and `--enable-ld-version-script` and building `Pillow` on top of it using the `intel` toolchain, on CentOS 7.4...

For @schiotz it worked fine as long as `LibTIFF` was also built with the `intel` toolchain (even with `--enable-ld-version-script` included), cfr. #7056 .

@schiotz Do you have it figured out why you were seeing the problem, but I am not?

**Comment by schiotz** [comment]
> @schiotz Do you have it figured out why you were seeing the problem, but I am not?

No.  And I have no clue how to investigate it.  However, I doubt that it only happens to me, since somebody had also made intel versions of LibTIFF with the two previous Intel toolchains, presumably because they had to.

**Comment by JackPerdue** [comment]
/sw/eb/software/LibTIFF/4.0.9-GCCcore-7.3.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `_end'
    error: command 'icc' failed with exit status 1

Got that today trying to build Pillow/5.3.0-intel-2018b-Python-3.6.6.  CentOS 6.

**Comment by schiotz** [comment]
@JackPerdue That is strange.  Why is it trying to use LibTIFF/4.0.9-GCCcore ?  It should use LibTIFF/4.0.9-intel-2018b, that module works with Pillow.  Are you sure your .eb files are up-to-date and that LibTIFF-4.0.9-intel-2018b.eb is available?
