### ISSUE TITLE
Libint-2.6.0-GCC-10.2.0-lmax-6-cp2k.eb Failure at install stage

### ISSUE THREAD

**Issue by oxford-arc** [easybuilders/easybuild-easyconfigs#12355]
EasyBuild: 4.3.3
OS: CentOS 8.1

Hi,

I am in the process of building CP2K 8.1 which requires Libint 2.6.0 - but the CP2K optimised "Libint-2.6.0-GCC-10.2.0-lmax-6-cp2k.eb" seems to build and test but fail during install with the following issue:

```
/usr/bin/install -c -m 0644 /apps/system/easybuild/build/Libint/2.6.0/GCC-10.2.0-lmax-6-cp2k/libint-2.6.0/libint-2.6.0/./lib/basis/* /apps/system/easybuild/software/Libint/2.6.0-GCC-10.2.0-lmax-6-cp2k/share/libint/2.6.0/basis
(cd fortran && make) || exit 1
make[1]: Entering directory '/apps/system/easybuild/build/Libint/2.6.0/GCC-10.2.0-lmax-6-cp2k/libint-2.6.0/libint-2.6.0/fortran'
g++ -E -DHAVE_CONFIG_H -D__COMPILING_LIBINT2=1 -D__COMPILING_LIBINT2=1 -I../include -I..//include -I/apps/system/easybuild/software/Python/2.7.18-GCCcore-10.2.0/include -I/apps/system/easybuild/software/Eigen/3.3.8-GCCcore-10.2.0/include -I/apps/system/easybuild/software/Boost/1.74.0-GCC-10.2.0/include -I/apps/system/easybuild/software/GMP/6.2.0-GCCcore-10.2.0/include  -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -std=c++11   ../include/libint2.h > ../include/libint2.h.i
python c_to_f.py ../include/libint2.h.i libint2_types_f.h Libint_t
grep '^#' ../include/libint2_types.h | grep -v '#include' > fortran_incldefs.h
FC libint_f.o
../include/libint2/util/generated/libint2_params.h:29:0:

   29 | #    if __has_include(<libint2_params.h>)
      |
Error: missing '(' before "__has_include" operand
../include/libint2/util/generated/libint2_params.h:29:0: Error: operator "__has_include" requires a header-name
make[1]: *** [../MakeSuffixRules:12: libint_f.o] Error 1
make[1]: Leaving directory '/apps/system/easybuild/build/Libint/2.6.0/GCC-10.2.0-lmax-6-cp2k/libint-2.6.0/libint-2.6.0/fortran'
make: *** [Makefile:38: fortran] Error 1
 (at easybuild/software/EasyBuild/4.3.3/lib/python3.6/site-packages/easybuild/tools/run.py:533 in parse_cmd_output)
```

The installation works fine on CentOS 7.7 so looks like a CentOS 8.1 compatibility issue.

Anyone know of a workaround for this?

Andy

**Comment by oxford-arc** [comment]
I see there is a patch to GCCcore 10.2.0 for this - I am rebuilding this now - hopefully this will fix.

Andy

**Comment by branfosj** [comment]
Yes, the patched GCCcore (from https://github.com/easybuilders/easybuild-easyconfigs/pull/11627) is to fix the the issue you see here. I've built `Libint-2.6.0-GCC-10.2.0-lmax-6-cp2k.eb` on CentOS 8.2 with that fix in place.

**Comment by oxford-arc** [comment]
Yes it fixed it. :-)
