### PR TITLE
Fix #9274, Qt5/5.13.1-GCCcore-8.3.0 depends on JasPer.

### LINKED ISSUE #9274: Qt5/5.13.1-GCCcore-8.3.0 depends on JasPer.
I'm trying to build Qt5/5.13.1-GCCcore-8.3.0 on RHEL8 and it fails on:

```
qjp2handler.cpp:47:10: fatal error: jasper/jasper.h: No such file or directory
 #include <jasper/jasper.h>
          ^~~~~~~~~~~~~~~~~
```

JasPer is not set as a dependency for Qt5/5.13.1-GCCcore-8.3.0 and there is no JasPer/2.0.14-GCCcore-8.3.0 available. I'm mostly wondering if this is a RHEL8 issue since this hasn't been seen before? There is a jasper-devel package available in the OS, but there are no osdeps either in the package.

For what its worth, JasPer/2.0.14 builds fine with GCCcore 8.3.0 and Qt5/5.13.1-GCCcore-8.3.0 builds fine once JasPer/2.0.14-GCCcore-8.3.0 is installed and added as a dependency.

### PR DESCRIPTION
**Pull request by terjekv**
- Qt5 depends on JasPer, which is missing from the spec.
  - Add JasPer for GCCcore-8.3.0.
  - Resolves #9274
  - No longer relies on locally built binutils that were installed due to testing of the issues found in #9182

### CODE REVIEW

File: easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb [hunk 1]
```diff
@@ -34,7 +34,8 @@ builddependencies = [
     ('gperf', '3.1'),
     ('Ninja', '1.9.0'),
     ('Python', '3.7.4'),
-    ('re2c', '1.2.1')
+    ('re2c', '1.2.1'),
+    ('JasPer', '2.0.14'),
```
Comment (boegel) [inline easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb]: @terjekv You shouldn't add `JasPer` both as build dep and runtime dep.

If a dependency is listed in `dependencies`, it will already be loaded at build time too.

This is also why the test fails, you're adding `JasPer` twice in the same dependency graph.

Comment (terjekv) [reply easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb]: Aha, thanks! I'll fix it later today!
