### ISSUE TITLE
Python-3.7.4-GCCcore-8.3.0.eb crashes in the fetching stage

### ISSUE THREAD

**Issue by jordiblasco** [easybuilders/easybuild-easyconfigs#10556]
The Python-3.7.4-GCCcore-8.3.0.eb recipe crashes in the fetching stage.
I'm working in a Ubuntu 18.04.3 LTS which still uses Python 2.7. 

```
== 2020-04-30 23:14:55,947 filetools.py:553 INFO Downloaded file pip_urls.html from url https://pypi.python.org/simple/pip to /tmp/eb-Wb8q97/tmpihgyUa/pip_urls.html
== 2020-04-30 23:14:55,947 filetools.py:585 INFO Successful download of file pip_urls.html from url https://pypi.python.org/simple/pip to path /tmp/eb-Wb8q97/tmpihgyUa/pip_urls.html
== 2020-04-30 23:14:55,967 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Traceback (most recent call last):
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/main.py", line 113, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3105, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3013, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 2883, in run_step
    step_method(self)()
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/easyblocks/generic/configuremake.py", line 180, in fetch_step
    super(ConfigureMake, self).fetch_step(*args, **kwargs)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 1770, in fetch_step
    self.exts = self.fetch_extension_sources(skip_checksums=skip_checksums)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 520, in fetch_extension_sources
    src_fn = self.obtain_file(fn, extension=True, urls=source_urls, force_download=force_download)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 727, in obtain_file
    alt_url = derive_alt_pypi_url(fullurl)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/tools/filetools.py", line 492, in derive_alt_pypi_url
    cand_urls = pypi_source_urls(pkg_name)
  File "/app/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/tools/filetools.py", line 471, in pypi_source_urls
    parsed_html = ElementTree.parse(urls_html)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 143, column 306
 (at easybuild/main.py:146 in build_and_install_software)
```

**Comment by lukazivulovic** [comment]
I have the same issue on Centos 7.7. My guess would be the redirects are not handled correctly: https://pypi.python.org/simple/pip > https://pypi.org/simple/pip > https://pypi.org/simple/pip/

**Comment by jfgrimm** [comment]
I'm facing an identical crash message when building Python-2.7.16-GCCcore-8.3.0.eb
Looking at the logs, it looks like easybuild fails to parse `pip_urls.html`, which was successfully downloaded. Line 143 corresponds to:
`<a href="https://files.pythonhosted.org/packages/60/65/16487a7c4e0f95bb3fc89c2e377be331fd496b7a9b08fd3077de7f3ae2cf/pip-20.0-py    2.py3-none-any.whl#sha256=eea07b449d969dbc8c062c157852cf8ed2ad1b8b5ac965a6b819e62929e41703" data-requires-python="&gt;=2.7,!=3.0.*,    !=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*" data-yanked>pip-20.0-py2.py3-none-any.whl</a><br/>`
I presume that the `data-yanked` attribute may be causing the problem?

**Comment by jfgrimm** [comment]
There's a bugfix available, see: https://github.com/easybuilders/easybuild/issues/619

**Comment by boegel** [comment]
I overlooked this issue, sorry. But the problem is indeed fixed (via https://github.com/easybuilders/easybuild-framework/pull/3303), fix is included in EasyBuild v4.2.1 or more recent versions (ad meanwhile the underlying issue has also been fixed in PyPI itself).
