### ISSUE TITLE
GCC 10.3.0 fails to compile on Ubuntu22.04-gcc version 11.4.0

### ISSUE THREAD

**Issue by Septemberrrrrr** [easybuilders/easybuild-easyconfigs#20020]
I just came into contact with EasyBuild, and some details did not know much. When I built the following problems, the following problems occurred.

eb -D GCCcore-10.3.0.eb 
output:
```
CFGS=/a/apps/eb/EasyBuild/4.8.2/easybuild/easyconfigs
 * [x] $CFGS/m/M4/M4-1.4.19.eb (module: M4/1.4.19)
 * [x] $CFGS/b/Bison/Bison-3.8.2.eb (module: Bison/3.8.2)
 * [x] $CFGS/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [x] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [x] $CFGS/b/binutils/binutils-2.36.1.eb (module: binutils/2.36.1)
 * [ ] $CFGS/g/GCCcore/GCCcore-10.3.0.eb (module: GCCcore/10.3.0)
Dry run: printing build status of easyconfigs and dependencies
CFGS=/a/apps/eb/EasyBuild/4.8.2/easybuild/easyconfigs
 * [x] $CFGS/m/M4/M4-1.4.19.eb (module: M4/1.4.19)
 * [x] $CFGS/b/Bison/Bison-3.8.2.eb (module: Bison/3.8.2)
 * [x] $CFGS/f/flex/flex-2.6.4.eb (module: flex/2.6.4)
 * [x] $CFGS/z/zlib/zlib-1.2.11.eb (module: zlib/1.2.11)
 * [x] $CFGS/b/binutils/binutils-2.36.1.eb (module: binutils/2.36.1)
 * [ ] $CFGS/g/GCCcore/GCCcore-10.3.0.eb (module: GCCcore/10.3.0)
```

Commands used:
eb GCCcore-10.3.0.eb -r

The console input log is as follows：
```
== 2024-03-04 11:12:41,588 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): cmd " ./configure --prefix=/tmp/eb-build/GCCcore/10.3.0/system-system/gcc-10.3.0/stage2_stuff --with-pic --disable-shared --enable-cxx  --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu" exited with exit code 1 and output:
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking compiler gcc -O2 -pedantic -fomit-frame-pointer -m64 ... no
checking ABI=x32
checking compiler gcc -O2 -pedantic -fomit-frame-pointer -mx32 ... no
checking ABI=32
checking compiler gcc -m32 -O2 -pedantic -fomit-frame-pointer ... no
checking compiler gcc -O2 -pedantic -fomit-frame-pointer ... no
configure: error: could not find a working compiler, see config.log for details
 (at easybuild/tools/run.py:681 in parse_cmd_output)
== 2024-03-04 11:12:41,588 build_log.py:267 INFO ... (took 13 mins 15 secs)
== 2024-03-04 11:12:41,588 filetools.py:2012 INFO Removing lock /a/apps/eb/EasyBuild/4.8.2/_a_apps_eb_GCCcore_10.3.0.lock...
== 2024-03-04 11:12:41,594 filetools.py:383 INFO Path /a/apps/eb/EasyBuild/4.8.2/_a_apps_eb_GCCcore_10.3.0.lock successfully removed.
== 2024-03-04 11:12:41,594 filetools.py:2016 INFO Lock removed: /a/apps/eb/EasyBuild/4.8.2/_a_apps_eb_GCCcore_10.3.0.lock
== 2024-03-04 11:12:41,594 easyblock.py:4277 WARNING build failed (first 300 chars): cmd " ./configure --prefix=/tmp/eb-build/GCCcore/10.3.0/system-system/gcc-10.3.0/stage2_stuff --with-pic --disable-shared --enable-cxx  --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu" exited with exit code 1 and output:
checking build system type... x86_64-pc-linux-gnu
checking host system t
== 2024-03-04 11:12:41,595 easyblock.py:328 INFO Closing log for application name GCCcore version 10.3.0
```

/tmp/eb-build/GCCcore/10.3.0/system-system/gcc-10.3.0/stage2_stuff/gmp/config.log
```
int main () { return 0; }
configure:7030: result: no
configure:5926: checking compiler gcc -O2 -pedantic -fomit-frame-pointer
Test compile:
configure:5940: gcc -O2 -pedantic -fomit-frame-pointer  conftest.c >&5
/a/apps/eb/binutils/2.36.1/bin/ld.gold: /tmp/eb-build/GCCcore/10.3.0/system-system/GCC_stage1_eb/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /a/apps/eb/binutils/2.36.1/bin/ld.gold)
collect2: error: ld returned 1 exit status
configure:5943: $? = 1
failed program was:
```

**Comment by jfgrimm** [comment]
@Septemberrrrrr in general, it's not straightforward to bootstrap compilers with older major versions than your system compiler.

filtering the `binutils` dependency in the toolchain can sometimes help; I believe we have built `GCC/10.3.0` on Ubuntu 22.04 at our site, by setting `EASYBUILD_FILTER_DEPS='binutils=:2.37['`

**Comment by Septemberrrrrr** [comment]
> @Septemberrrrrr in general, it's not straightforward to bootstrap compilers with older major versions than your system compiler.
> 
> filtering the `binutils` dependency in the toolchain can sometimes help; I believe we have built `GCC/10.3.0` on Ubuntu 22.04 at our site, by setting `EASYBUILD_FILTER_DEPS='binutils=:2.37['`

Thanks! I tried building using the following command and it looks like it succeeded. `export EASYBUILD_FILTER_DEPS='binutils=:2.37[' && eb GCCcore-10.3.0.eb -r`
But does this mean that I need to do this for any other module that comes across a compiler older than the system's?For example "GCCcore-6.4.0.eb"?
Thank you for your support!

**Comment by Micket** [comment]
Yes building old compilers with new OS is often just straight up broken. 
Starting with 5.0.x we will be much more aggressive in pruning off deprecated toolchains.
You should consider anything older than foss-2021a (GCC 10.3.0) already dead and gone. Not only are the compilers old and janky, but all the software in those old toolchains have mostly bitrotted.

**Comment by crubb** [comment]
Thank you - That helped me build `GCCcore-10.3.0.eb`, as well. But, as soon as I want to build `zlib-1.2.11-GCCcore-10.3.0.eb`, I ran into the same error:

```
[...]
gcc -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -D_LARGEFILE64_SOURCE=1 -DNO_STRERROR -DNO_vsnprintf -DHAVE_HIDDEN -o minigzip64 minigzip64.o -L. libz.a
/project/eb/software/binutils/2.36.1/bin/ld.gold: /project/eb/software/GCCcore/10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /project/eb/software/binutils/2.36.1/bin/ld.gold)
collect2: error: ld returned 1 exit status
/project/eb/software/binutils/2.36.1/bin/ld.gold: /project/eb/software/GCCcore/10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /project/eb/software/binutils/2.36.1/bin/ld.gold)
collect2: error: ld returned 1 exit status
make: *** [Makefile:289: example] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:292: minigzip] Error 1
/project/eb/software/binutils/2.36.1/bin/ld.gold: /project/eb/software/GCCcore/10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /project/eb/software/binutils/2.36.1/bin/ld.gold)
collect2: error: ld returned 1 exit status
make: *** [Makefile:301: example64] Error 1
/project/eb/software/binutils/2.36.1/bin/ld.gold: /project/eb/software/GCCcore/10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /project/eb/software/binutils/2.36.1/bin/ld.gold)
collect2: error: ld returned 1 exit status
make: *** [Makefile:304: minigzip64] Error 1
 (at easybuild/tools/run.py:695 in parse_cmd_output)
== 2025-02-05 21:43:27,773 filetools.py:2025 INFO Removing lock /project/eb/software/.locks/_project_eb_software_zlib_1.2.11-GCCcore-10.3.0.lock...
== 2025-02-05 21:43:27,773 filetools.py:385 INFO Path /project/eb/software/.locks/_project_eb_software_zlib_1.2.11-GCCcore-10.3.0.lock successfully removed.
== 2025-02-05 21:43:27,773 filetools.py:2029 INFO Lock removed: /project/eb/software/.locks/_project_eb_software_zlib_1.2.11-GCCcore-10.3.0.lock
== 2025-02-05 21:43:27,773 easyblock.py:4297 WARNING build failed (first 300 chars): cmd " make  -j 48 " exited with exit code 2 and output:
gcc -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -D_LARGEFILE64_SOURCE=1 -DNO_STRERROR -DNO_vsnprintf -DHAVE_HIDDEN -I. -c -o example.o test/example.c
gcc -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -D_LARGEFILE64_SOURC
== 2025-02-05 21:43:27,774 easyblock.py:326 INFO Closing log for application name zlib version 1.2.11
```

I had upgraded to the latest EasyBuild:
```
This is EasyBuild 4.9.4 (framework: 4.9.4, easyblocks: 4.9.4) on host radbert.
```

Is there any way to fix that more reliably?

Thanks!

**Comment by Micket** [comment]
> I had upgraded to the latest EasyBuild:

I'm afraid that makes no difference.

> /project/eb/software/binutils/2.36.1/bin/ld.gold

it does not seem like you filtered this out like you seem to indicate.

> Is there any way to fix that more reliably?

No. Everyone should consider these super old toolchains dead already and only use the new ones.

**Comment by crubb** [comment]
Unfortunately, FSL is not available in for newer toolchains.

I thought I had to filter only for the GCCcore build, but I gather I have to do it for everything.

Thanks!

**Comment by Micket** [comment]
> Unfortunately, FSL is not available in for newer toolchains.

Yes all software needs to be continuously updated, so one should expect to do the work to write new easyconfig, update versions of it and all of the dependencies, check any patches that might need updating and for any new flags and whatnot, then upload a new PR with the new easyconfigs and patches and then also do a test report to confirm that the software works as expected.
