### PR TITLE
{bio}[foss/2023a] pyTME v0.1.6 /w CUDA 12.1.1

### PR DESCRIPTION
**Pull request by ThomasHoffmann77**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**FAILED**
Build succeeded for 3 out of 4 (3 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/48729bb4cbd3cba8e6c02b41ffb3295e for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/4f3c60cf490af0199ced8a28e6157308 for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**SUCCESS**
Build succeeded for 0 out of 0 (3 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/60a4a397d93a5ad384af7cc90ca33c2b for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**FAILED**
Build succeeded for 1 out of 3 (6 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/dfcccd87696ced64a8cad347055edad6 for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**FAILED**
Build succeeded for 0 out of 2 (6 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/9f8d87068c021bbbee47eeb18df266e0 for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**FAILED**
Build succeeded for 0 out of 2 (7 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/1ef026d81ffb48d4265e348c2321a22a for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**FAILED**
Build succeeded for 2 out of 3 (7 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/0885fe8e76a35d337f40b0230390a594 for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**SUCCESS**
Build succeeded for 0 out of 0 (5 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/caa9f3a0d67e54b4f542c7b5036625f6 for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/b0a2112a1f875e261fc111fdcf7465a7 for a full test report.

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 10 out of 12 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/fda51cebd7fb00ccf8fd82d91ebe5416 for a full test report.

**Review by jfgrimm — CHANGES_REQUESTED** [review]

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/69fa98ef79c4b33e7bce5cc2c25bad66 for a full test report.

**Comment by ThomasHoffmann77** [comment]
Test report by @thomashoffmann77
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
srv-mahamid-01.embl.de - Linux AlmaLinux 8.8, x86_64, AMD EPYC 7513 32-Core Processor, 2 x NVIDIA NVIDIA GeForce RTX 3090, 535.113.01, Python 3.6.8
See https://gist.github.com/ThomasHoffmann77/c1c1b60c42139a2b07d8542814723329 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node3304.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/94bfdb6584f10899be8cec8f70c56135 for a full test report.

**Comment by boegel** [comment]
> @boegel I don't understand the errors:
> ```
> == 2024-05-23 11:55:07,543 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): `/user/gent/400/vsc40023/eb_scratch/RHEL8/cascadelake-volta-ib/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check` failed:
> npe2 0.7.4 has requirement build>=1, but you have build 0.10.0.
> jupyter-events 0.7.0 has requirement jsonschema[format-nongpl]>=4.18.0, but you have jsonschema 4.17.3.
> 
> ```
> build 1.1.1 should be provided by napari 0.4.19post1 and jsonschema 4.18.0 by jupyter-server 2.7.2

The order in which dependencies are specified could matter here, or perhaps some things should be a build-only dependency (`build` 0.10.0 is provided by `poetry-1.5.1-GCCcore-12.3.0.eb`, for example, which should not be a runtime dependency).

**Comment by sassy-crick** [comment]
@ThomasHoffmann77 You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```
Also, the conflicts must be resolved so please check which of your EasyConfigs has meanwhile a merged version in `EasyBuild-5.1.0`

**Comment by ThomasHoffmann77** [comment]
> @ThomasHoffmann77 You might want to sync your PR with development, something like this:
> 
> ```
> eb --sync-pr-with-develop NUMBER_OF_PR
> ```
> 
> Also, the conflicts must be resolved so please check which of your EasyConfigs has meanwhile a merged version in `EasyBuild-5.1.0`

@sassy-crick @maurerv I'll work on an update for pyTME v0.3.0b0
