### PR TITLE
Reframe 462

### PR DESCRIPTION
**Pull request by casparvl**
I had a close look at https://github.com/easybuilders/easybuild-easyconfigs/pull/20911 and https://github.com/easybuilders/easybuild-easyconfigs/pull/21189 and discussed a bit on the maintainers chat how to proceed with ReFrame: do we put it at a toolchain level, or not.

Consensus was that if there is good reason, we can do both. This PR adds both options. It also

- Correctly lists dependencies (as `osdependencies` in case of the `SYSTEM` toolchain, and regular `dependencies` in case of the `GCCcore` toolchain
- It does not include `binutils as build dep. Was there in https://github.com/easybuilders/easybuild-easyconfigs/pull/20911but doesn't make sense imho, since nothing is compiled for this installation.
- It does not include `req_py_majver` and `req_py_minver` for the configs at `GCCcore` level, as these only apply to the `SYSTEM` toolchain
- It does not include all ReFrame deps in `exts_list`, but rather, depends on ReFrame to install all in the `%(installdir)/external` directory. This is how ReFrame's was _designed_ to work. The bootstrap install requires no build dependencies at all. At runtime, the `reframe` command adds the `%(installdir)/external` to the `sys.path` before executing the rest of the ReFrame code. From this moment onward, as soon as `reframe` finds a reframe test that includes a `import reframe`, that import works, since all the deps are on the `sys.path`. These deps are NOT on the `PYTHONPATH` on purpose: this way, `reframe` can run in an isolated manner, without affecting how other code (e.g. code from the tests) run.
- We set `RFM_PURGE_ENVIRONMENT` by default for the ReFrame versions at `GCCcore` toolchain level. This is a sensible default, since the toolchain will now be loaded when the `reframe` command is run, and one wants to unload it when running a test. Note that this behavior can still be overwritten in a local ReFrame config file, it merely gives a reasonable default for this type of installation.
- We disable all kind of standard python-package sanity checks from EasyBuild, as they are _expected_ to fail for ReFrame's setup. First, `download_dep_fail` is disabled, since we intentionally let ReFrame's bootstrap script download all dependencies. Second, `sanity_pip_check` is disabled, since this pip check will rely on the dependencies being on `PYTHONPATH` (and they are not, they are included in the `sys.path` as part of the `reframe` command). Third, we set `modulename` to `False` so that no `python -c "import reframe"` is done as part of the `sanity_check`. This is expected to fail, as it would require the dependencies to be on the `PYTHONPATH`.
- Removed all manual additions to `PYTHONPATH`
- No longer manually copy `hpctestlib`. It is now installed by default by ReFrame's installation method. See https://github.com/reframe-hpc/reframe/releases/tag/v4.3.4
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21189 sets `BASH_COMPLETION_USER_DIR` as environment variable, but that is not needed. The `share` directory is automatically added by EasyBuild to `XDG_DATA_DIRS`. This seems to be enough, at least my auto-complete for `reframe` arguments seemed to work just fine without setting `BASH_COMPLETION_USER_DIR`.

### CODE REVIEW

**Comment by casparvl** [comment]
@boegelbot please test @jsc-zen3

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 0 out of 0 (3 easyconfigs in total)
login3.karolina.it4i.cz - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/casparvl/2f543f120cedfb2ff3863cbbc7b931b3 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
login3.karolina.it4i.cz - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/casparvl/593439c86b43d1ec0dbdd8f799ed2a23 for a full test report.

**Comment by casparvl** [comment]
From @branfosj : On Generoso `ls -l /usr/lib* | grep xslt` gives nothing. So, it seems that OS dep is really missing there. I'm assuming the same is true on `jsczen3`. 

Note that `libxslt` is a dependency for `lxml` (https://pypi.org/project/lxml/ ), which provides bindings to the `libxml2` and `libxslt` libraries. `lxml` is one of the dependencies for ReFrame (see ReFrame's [requirements.txt](https://github.com/reframe-hpc/reframe/blob/v4.6.2/requirements.txt )).

So, those failures are expected, and not an issue with the EasyConfigs. I'll rerun for only the `GCCcore` level EasyConfigs.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="ReFrame-4.6.2-GCCcore-12.3.0.eb ReFrame-4.6.2-GCCcore-13.2.0.eb"

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="ReFrame-4.6.2-GCCcore-12.3.0.eb ReFrame-4.6.2-GCCcore-13.2.0.eb"

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
cn563.karolina.it4i.cz - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/casparvl/7effd6a634917af4eb0f8d857ea07117 for a full test report.

**Comment by casparvl** [comment]
@boegelbot please test @ jsc-zen3
EB_ARGS="ReFrame-4.6.2-GCCcore-12.3.0.eb ReFrame-4.6.2-GCCcore-13.2.0.eb"

**Comment by casparvl** [comment]
Test report by @casparvl
**FAILED**
Build succeeded for 11 out of 13 (3 easyconfigs in total)
cn0586 - Linux RHEL 8.8, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/4f8c993359cbe220e9fbe6c1221baaf4 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
cn0202 - Linux RHEL 8.8, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/99592e75ca8c7e8dcbdfc88b78a0c7ad for a full test report.

**Comment by casparvl** [comment]
Note: I haven't added `cURL` as builddep for the `SYSTEM` toolchain. There was no issue there for https://github.com/easybuilders/easybuild-easyconfigs/pull/21269#issuecomment-2315134191 Also, there is no `cURL` yet at system toolchain, and I think we can reasonably expect a bit more on the `SYSTEM` toolchain level.

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="ReFrame-4.6.2-GCCcore-12.3.0.eb ReFrame-4.6.2-GCCcore-13.2.0.eb"

**Comment by casparvl** [comment]
@boegelbot please test @ generoso
EB_ARGS="ReFrame-4.6.2-GCCcore-12.3.0.eb ReFrame-4.6.2-GCCcore-13.2.0.eb"

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
cn574.karolina.it4i.cz - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7H12 64-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/casparvl/e0b953c47b68e592a74ae96b02671c62 for a full test report.

**Comment by casparvl** [comment]
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/casparvl/aaa00ea2080a4b248ed5dde5932d0e95 for a full test report.

**Comment by bedroge** [comment]
I get this on my Ubuntu system:
```
ERROR: Failed to process easyconfig /tmp/eb-ydrcc1tb/files_pr21269/r/ReFrame/ReFrame-4.6.2.eb: One or more OS dependencies were not found: [('libxslt',)]
```
Apparently, the package is named `libxslt1.1` on Ubuntu/Debian? https://packages.debian.org/search?searchon=sourcenames&keywords=libxslt

File: easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2.eb [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+description = '''ReFrame is a framework for writing regression tests for HPC systems.'''
+
+toolchain = SYSTEM
+
+allow_system_deps = [('Python', SYS_PYTHON_VERSION)]
+
+# Required by lxml, which is installed by ReFrame's bootstrap installer
+osdependencies = [
+    ('libxml2'),
+    ('libxslt'),
```
Comment (bedroge) [inline easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2.eb:16]:
```suggestion
    ('libxslt', 'libxslt1.1'),
```

This solves the issue with libxslt, but now the installation of setuptools fails:
```
  File "/data/eb/build/ReFrame/4.6.2/system-system/setuptools/setuptools-59.6.0/pkg_resources/__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```
This has been removed in Python 3.12 (see https://docs.python.org/3/whatsnew/3.12.html#importlib), which is the default Python on Ubuntu 24.04. But bumping the setuptools version would break Python 3.6 support...

Comment (casparvl) [reply easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2.eb:16]: This, exactly this stuff is the problem with a ReFrame at `SYSTEM` toolchain level. But I know some people still really prefer it, which is why I tried to push one (but with proper osdeps and everything).

Ok, so we have two choices: support 3.6-3.11, or bump setuptools and support 3.7-3.12? How far would you need to bump setuptools, would it still support 3.7? I see 68.0.0 is the latest that supports 3.7, is that high enough to resolve your issue?

Comment (casparvl) [reply easybuild/easyconfigs/r/ReFrame/ReFrame-4.6.2.eb:16]: Seems to have been fixed in `66.1.0` https://github.com/pypa/setuptools/commit/6653e747c3815b140156249205397ef3719581ee . That would give us a small window of versions that should work with both 3.7 and 3.12...

**Comment by casparvl** [comment]
I'm splitting the system toolchain EasyConfig into a seperate PR, since it still has issues. The rest _should_ be ready to be merged.

**Comment by casparvl** [comment]
Split off at https://github.com/easybuilders/easybuild-easyconfigs/pull/21307

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 24.04.1 LTS (Noble Numbat), x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.12.3
See https://gist.github.com/bedroge/736e2c1108ec059ecdbb8fa35397bb76 for a full test report.

**Comment by bedroge** [comment]
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/210c6f6b61bfec7f09c61e734d87efc1 for a full test report.

**Review by bedroge — APPROVED** [review]
Lgtm!

**Comment by bedroge** [comment]
Going in, thanks @casparvl!

**Comment by akesandgren** [comment]
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-cn1613.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, Python 3.10.12
See https://gist.github.com/akesandgren/7abec5b1014824f435cdfc139f97c25f for a full test report.
