### PR TITLE
add patches for Qt5 5.15.5 to fix compilation failures in abseil and breakpad with glibc 2.34

### LINKED ISSUE #17059: Qt5/5.15.5-GCCcore-11.3.0 fails to build on Ubuntu 22.04
During the build of `Qt5/5.15.5-GCCcore-11.3.0` on my Ubuntu 22.04 system, I got the following error:
```
/failure_signal_handler.cc: In function 'bool absl::SetupAlternateStackOnce()':
../../../../git/src/3rdparty/chromium/third_party/abseil-cpp/absl/debugging/failure_signal_handler.cc:138:32: error: no matching function for call to 'max(long int, int)'
```

Apparently, it's related to the glibc version:
https://bugs.gentoo.org/811312
That bug report also contains two patches, and they solved the issue for me. I don't know if it makes sense to always include them in the easyconfig, but at least I wanted to report the issue here in case other people run into the same issue.

### PR DESCRIPTION
**Pull request by bedroge**
Fixes #17059

### CODE REVIEW

**Comment by bedroge** [comment]
@boegelbot please test @ jsc-zen2
CORE_CNT=16

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d4b27013d6ceef18b6d6033c41cc35ed for a full test report.

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node087.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2367d7bd3c5f25a9716a43bede338866 for a full test report.

**Comment by jfgrimm** [comment]
not sure what happened to my first build, maybe too much parallelism

**Review by jfgrimm — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
Going in, thanks @bedroge!
