### PR TITLE
add patch to fix linking error for imread extension in scikit-image easyconfigs using intel toolchain

### LINKED ISSUE #14219: "multiple definition of" linking error when building scikit-image with intel toolchain
Installing `scikit-image-0.18.1-intel-2020b.eb` has started failing for me recently, with:

```
  ld: /software/LibTIFF/4.1.0-GCCcore-10.2.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `_end'
  ld: /software/LibTIFF/4.1.0-GCCcore-10.2.0/lib/libtiff.so:(*IND*+0x0): multiple definition of `__bss_start'
  error: command 'icpc' failed with exit status 1
  Building wheel for imread (setup.py): finished with status 'error'
```

It seems like the trigger for this problem are the changes made in #14079; the problem does not occur if `LibTIFF` was installed with the `LibTIFF-4.1.0-GCCcore-10.2.0.eb` that is included in EasyBuild v4.4.2 (which does not have the additional dependencies that were added in #14079).

This looks very similar to the problems reported in #6953, which never got resolved...
However, the `--enable-ld-version-script` was already there in `LibTIFF-4.1.0-GCCcore-10.2.0.eb`, it was not introduced with #14079.

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)
fixes #14219

### CODE REVIEW

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3103.skitty.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b4209eed88d40314702e8251a055b4f2 for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3524.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c1abb3984712343dbcca8c2f2ae9919a for a full test report.

**Review by smoors — APPROVED** [review]
lgtm

**Comment by smoors** [comment]
Going in, thanks @boegel!
