### PR TITLE
{bio}  [foss/2015a, goolf-1.4.10] Tophat 2.0.12 and SAMtools 0.1.18 (REVIEW)

### PR DESCRIPTION
**Pull request by rjeschmi**
Just adding a modified name note

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
missing dep: `Boost/1.55.0-foss-2015a-Python-2.7.9`, missing `easyblock` spec in `TopHat` easyconfig?

**Comment by rjeschmi** [comment]
yeah sorry the dep must have been lost at some point. 

In any case, I'll maybe pull it forward as 1.57.0

**Comment by boegel** [comment]
works for me, try and include a proper zlib dep in the Boost easyconfig, cfr. https://github.com/hpcugent/easybuild-easyconfigs/issues/1475

**Comment by rjeschmi** [comment]
hmm @pescobar is sticking with 1.55.0 here

https://github.com/hpcugent/easybuild-easyconfigs/pull/1476

I'd rather keep them all the same since we are likely to have the same users/bugs

**Comment by boegel** [comment]
sure, they should be the same... @pescobar: did you have a good reason to stick with Boost v1.55?

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
@rjeschmi: missing dep?

**Comment by boegel** [comment]
Boost dep resolved now that #1351 is merged in?

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in this PR)
Linux SL 6.6, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.6.6
See https://gist.github.com/a5fa074e289b5f6f0ed4 for a full test report.

**Comment by boegel** [comment]
TopHat build fails on my end:

```
./SeqAn-1.3/seqan/file/file_generated_forwards.h:927:66: error: invalid abstract return type ‘seqan::FileFormat<TFile, TData, TMeta, void>’
```

**Comment by fgeorgatos** [comment]
Hi, would dependency `('Boost', '1.58.0', '-Python-2.7.10')` be a good or, a bad thing in this case?

**Comment by fgeorgatos** [comment]
btw. life-science supporters need to converge asap in a variant of:
https://github.com/hpcugent/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/b/biodeps/biodeps-1.6-goolf-1.4.10-extended.eb
(or, suffer massive duplication of effort)

**Comment by rjeschmi** [comment]
The SeqAn problem is a problem :) I need to come up with a better solution. TopHat has a static include of an old version of seqan.

**Comment by fgeorgatos** [comment]
status of this?

**Comment by rjeschmi** [comment]
@fgeorgatos I think with tophat 2.0.13 looking like it will get merged (based on goolf-1.7.20) we will perhaps look there for the biodeps.

I'm considering just closing this PR for now and focusing the effort elsewhere.

**Comment by boegel** [comment]
@rjeschmi: #1476, any changes needed here?

**Comment by rjeschmi** [comment]
I feel like I should close this and focus on tophat in goolf-1.7.20.

It will be easier, to compile...

**Comment by boegel** [comment]
What's the issue with `foss/2015a` here, compared to `goolf/1.7.20`?

Having easyconfigs that work with `foss/2015a` would be tremendously valuable.

**Comment by rjeschmi** [comment]
Yes, tophat won't build with gcc 4.9.x

1.7.20 is 4.8.4

https://groups.google.com/forum/#!topic/tuxedo-tools-users/M7Z9zLuu8o4

**Comment by boegel** [comment]
Sure it will, just needs a tiny patch, see https://github.com/rjeschmi/easybuild-easyconfigs/pull/6 ;-)

**Comment by migueldiascosta** [comment]
@rjeschmi, this PR is being closed for the following reason(s): no activity for > 6 months.
Please don't hesitate to reopen this PR or add a comment if you feel this contribution is still relevant.
For more information on our policy w.r.t. closing PRs, see https://easybuild.readthedocs.io/en/latest/Contributing.html#why-a-pull-request-may-be-closed-by-a-maintainer
