### PR TITLE
[gompi/2022.05] in-place update to netCDF v4.9.0

### PR DESCRIPTION
**Pull request by boegel**
I intended to actually open #15676 with netCDF v4.9.0, but apparently I managed to screw that up 😅 

(opened as draft PR, because compilation fails even though it worked fine with v4.8.1...)

### CODE REVIEW

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by jfgrimm** [comment]
```
/project/boegelbot/Rocky8/haswell/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJreclaim':
ncjson.c:(.text+0xa50): multiple definition of `NCJreclaim'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text+0xac0): first defined here
/project/boegelbot/Rocky8/haswell/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJnew':
ncjson.c:(.text+0xb10): multiple definition of `NCJnew'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text+0xb80): first defined here
/project/boegelbot/Rocky8/haswell/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJnewstringn':
ncjson.c:(.text+0xb60): multiple definition of `NCJnewstringn'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text+0xbd0): first defined here
/project/boegelbot/Rocky8/haswell/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJnewstring':
ncjson.c:(.text+0xc20): multiple definition of `NCJnewstring'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text+0xc90): first defined here
/project/boegelbot/Rocky8/haswell/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJparse':
ncjson.c:(.text+0x1160): multiple definition of `NCJparse'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text+0x1080): first defined here
/project/boegelbot/Rocky8/haswell/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJdictget':
ncjson.c:(.text+0x1190): multiple definition of `NCJdictget'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text+0x11a0): first defined here
/project/boegelbot/Rocky8/haswell/software/binutils/2.38-GCCcore-11.3.0/bin/ld: ../liblib/libnetcdf.a(ncjson.c.o): in function `NCJcvt':
ncjson.c:(.text+0x1220): multiple definition of `NCJcvt'; CMakeFiles/nczhdf5filters.dir/NCZhdf5filters.c.o:NCZhdf5filters.c:(.text+0x1230): first defined here
```

**Comment by branfosj** [comment]
The:
```
# HDF5 version detection is missed in netCDF 4.8.1 when HDF5_C_LIBRARY, HDF5_INCLUDE_DIR, and HDF5_HL_LIBRARY are set
local_hdf5_version_fix = '-DHDF5_VERSION=$EBVERSIONHDF5'
```
is no longer needed.

Also, this issue is in building the static libs (`-DBUILD_SHARED_LIBS=OFF`). The failure does not happen when building the shared libs (`-DBUILD_SHARED_LIBS=ON`).

**Comment by boegel** [comment]
I've opened an issue upstream for this: https://github.com/Unidata/netcdf-c/issues/2419

**Comment by zao** [comment]
I commented with a bit of analysis in the upstream issue, a workaround for us may be to patch `netcdf_json.h` to have the function declarations and definitions `static` to prevent them from having linkage. Haven't tested this outside of a standalone repro case.

**Comment by boegel** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/d35ddebedb4d347ed05e0e7bd614a719 for a full test report.

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5069393d6e047eca078099ad4e25c203 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/4ad92b4dfecf8fc97272159ae476e08c for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3601.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/89f8e5a4dc87489ded04da5a791de61b for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/338898ca1d25185e90bd36c9cd895a45 for a full test report.
