### PR TITLE
{devel}[GCCcore/12.2.0] cpp-netlib v0.13.0, Boost v1.69.0

### PR DESCRIPTION
**Pull request by SimonPinches**
(created using `eb --new-pr`)

### CODE REVIEW

**Comment by sassy-crick** [comment]
@SimonPinches You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

**Comment by Crivella** [comment]
@boegelbot please test @ jsc-zen3

**Comment by Crivella** [comment]
Test report by @Crivella
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/0cad127c0aefc21c3c2f53ac24605b7e for a full test report.

File: easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    ('Boost', '1.69.0'),
+]
+
+# dependencies = [
+#     ('OpenSSL', '1.1', '', SYSTEM),
+# ]
+
+configopts = '-DCPP-NETLIB_STATIC_BOOST=ON '
+configopts += '-DCMAKE_POSITION_INDEPENDENT_CODE=ON'
+
```
Comment (Crivella) [inline easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb]:
```suggestion
configopts = '-DCPP-NETLIB_STATIC_BOOST=ON '

```

`CMAKE_POSITION_INDEPENDENT_CODE` is already set by `toolchainopts = {'pic': True}` and the `CMakeMake` Easyblock

File: easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+    ('zlib', '1.2.12'),
+    ('XZ', '5.2.7'),
+    ('ICU', '72.1'),
+]
+
+configopts = '--without-libraries=python,mpi'
+
+# Don't build boost_mpi
+boost_mpi = False
+boost_multi_thread = True
```
Comment (Crivella) [inline easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb]:
```suggestion
# disable MPI, build Boost libraries with tagged layout
boost_mpi = False
tagged_layout = True
```

Conform to newer EasyBlock

File: easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb [hunk 3]
```diff
@@ -0,0 +1,31 @@
+name = 'Boost'
+version = '1.69.0'
+
+homepage = 'https://www.boost.org/'
+description = """Boost provides free peer-reviewed portable C++ source libraries."""
+
+toolchain = {'name': 'GCCcore', 'version': '12.2.0'}
```
Comment (Crivella) [inline easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb]:
```suggestion
toolchain = {'name': 'GCC', 'version': '12.2.0'}
```

Boost is performance sensitive so we want it on top `GCC`

File: easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb [hunk 4]
```diff
@@ -0,0 +1,42 @@
+easyblock = 'CMakeMake'
+
+name = 'cpp-netlib'
+version = '0.13.0'
+
+homepage = 'https://cpp-netlib.org'
+description = """A collection of open-source libraries for high level network programming."""
+
+toolchain = {'name': 'GCCcore', 'version': '12.2.0'}
```
Comment (Crivella) [inline easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb]:
```suggestion
toolchain = {'name': 'GCC', 'version': '12.2.0'}
```

Same as above

File: easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+    'filename': '%(name)s-%(version)s-git.tar.gz',
+    'git_config': {
+        'url': 'https://github.com/cpp-netlib',
+        'repo_name': 'cpp-netlib',
+        'commit': 'cpp-netlib-0.13.0-final',
+        'recursive': True,
+        'keep_git_dir': True,
+    },
+}]
+checksums = ['75ae8c8ca5d2ecc01402b6bd7711d32688c6da5dc865711d14ca6e82aba508ae']
```
Comment (Crivella) [inline easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb]:
```suggestion
sources = [{
    'filename': '%(name)s-%(version)s-git.tar.xz',
    'git_config': {
        'url': 'https://github.com/cpp-netlib',
        'repo_name': 'cpp-netlib',
        'commit': 'cpp-netlib-0.13.0-final',
        'recursive': True,
        'keep_git_dir': False,
    },
}]
checksums = ['d356789167c20d554fc319ead1a2b830b321326b5900110911055549339727b5']
```

Needed for reproductible tarballs

File: easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb [hunk 6]
```diff
@@ -0,0 +1,31 @@
+name = 'Boost'
+version = '1.69.0'
```
Comment (Crivella) [inline easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb]:
```suggestion
version = '1.73.0'
```

See https://github.com/boostorg/thread/issues/364

File: easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+
+builddependencies = [
+    ('binutils', '2.39'),
+    ('CMake', '3.24.3'),
+    ('Boost', '1.69.0'),
```
Comment (Crivella) [inline easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb]:
```suggestion
    ('Boost', '1.73.0'),
```

From version change

**Review by Crivella — CHANGES_REQUESTED** [review]
This is a WIP review, concerning the changes i think we either need to use Boost>=1.73 to fix
https://github.com/boostorg/thread/issues/364
which then in turns requires us to either pull cpp-netlib from a newer commit including https://github.com/cpp-netlib/cpp-netlib/commit/d42fb59a64a60f8495179b71d88bf32e93448133 or to patch it out ourselves,

or use Boost-1.69  but patch out the problem related to `PTHREAD_STACK_MIN`

Also the checksums and filenames would need to be updated accordingly

File: easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb (hunk 2 above)
Comment (SimonPinches) [reply easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb]: @Crivella, I've switched to using Boost/1.81.0 - so changes to this EB file can be dropped.

File: easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb (hunk 3 above)
Comment (SimonPinches) [reply easybuild/easyconfigs/b/Boost/Boost-1.69.0-GCCcore-12.2.0.eb]: See last comment.

File: easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb (hunk 5 above)
Comment (SimonPinches) [reply easybuild/easyconfigs/c/cpp-netlib/cpp-netlib-0.13.0-GCCcore-12.2.0.eb]: @Crivella, sorry missed these changes before pushing some others so couldn't apply yours via GitHub web interface.  These changes are now included though.

**Comment by Crivella** [comment]
I am not sure `cpp-netlib` can work with newer versions with `1.73` i was only hitting

```
/home/crivella/.local/easybuild/build/cppnetlib/0.13.0/GCC-12.2.0/cpp-netlib/boost/network/protocol/stream_handler.hpp:22:10: fatal error: boost/asio/stream_socket_service.hpp: No such file or directory
   22 | #include <boost/asio/stream_socket_service.hpp>
```

which the commit i previously referenced applied as a patch might fix https://github.com/cpp-netlib/cpp-netlib/commit/d42fb59a64a60f8495179b71d88bf32e93448133

with `1.81` i am also hitting

```
/home/crivella/.local/easybuild/build/cppnetlib/0.13.0/GCC-12.2.0/cpp-netlib/boost/network/protocol/http/client/connection/async_base.hpp:62:18: error: ‘boost::network::http::impl::async_connection_base<boost::network::http::tags::http_async_8bit_udp_resolve, 1, 1>::resolver_type’ {aka ‘class boost::asio::ip::basic_resolver<boost::asio::ip::udp>’} has no member named ‘get_io_service’
```

**Comment by SimonPinches** [comment]
> I am not sure `cpp-netlib` can work with newer versions with `1.73` i was only hitting
> 
> ```
> /home/crivella/.local/easybuild/build/cppnetlib/0.13.0/GCC-12.2.0/cpp-netlib/boost/network/protocol/stream_handler.hpp:22:10: fatal error: boost/asio/stream_socket_service.hpp: No such file or directory
>    22 | #include <boost/asio/stream_socket_service.hpp>
> ```
> 
> which the commit i previously referenced applied as a patch might fix [cpp-netlib/cpp-netlib@d42fb59](https://github.com/cpp-netlib/cpp-netlib/commit/d42fb59a64a60f8495179b71d88bf32e93448133)
> 
> with `1.81` i am also hitting
> 
> ```
> /home/crivella/.local/easybuild/build/cppnetlib/0.13.0/GCC-12.2.0/cpp-netlib/boost/network/protocol/http/client/connection/async_base.hpp:62:18: error: ‘boost::network::http::impl::async_connection_base<boost::network::http::tags::http_async_8bit_udp_resolve, 1, 1>::resolver_type’ {aka ‘class boost::asio::ip::basic_resolver<boost::asio::ip::udp>’} has no member named ‘get_io_service’
> ```

Thanks @Crivella, I confess to making these changes somewhat blindly since this EB is no longer critical for us but I'll try to take a look soon to not lose momentum on this.  Do you prefer that I put lots of effort into trying to make `cpp-netlib` work with `Boost/1.81.0-GCC-12.2.0` or is it okay to introduce an older version since it's only a build dependency, as I did initially?

**Comment by Crivella** [comment]
I think it is fine to introduce an older version if it is simpler than patching `cpp-netlib` (especially if not officially supported)

**Comment by verdurin** [comment]
@SimonPinches are you still interested in this one? You mentioned it was no longer critical for you.
Happy to review it if you are.

**Comment by SimonPinches** [comment]
> @SimonPinches are you still interested in this one? You mentioned it was no longer critical for you. Happy to review it if you are.

As mentioned above, this is not critical for us and I don't really have time to invest in such an old toolchain so I'm happy to  move to focusing on more recent/relevant PRs.

**Comment by boegel** [comment]
> > @SimonPinches are you still interested in this one? You mentioned it was no longer critical for you. Happy to review it if you are.
> 
> As mentioned above, this is not critical for us and I don't really have time to invest in such an old toolchain so I'm happy to move to focusing on more recent/relevant PRs.

OK, we'll go ahead and close this then, makes more sense to focus on newer software/toolchain versions, indeed...
