### PR TITLE
{bio}[gompi/2020b] MrBayes v3.2.6

### PR DESCRIPTION
**Pull request by boegel**
(created using `eb --new-pr`)

### CODE REVIEW

File: easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-gompi-2020b.eb [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+builddependencies = [
+    ('Autotools', '20200321'),
+]
+
+dependencies = [
+    ('libreadline', '8.0'),
+    ('beagle-lib', '3.1.2'),
+]
+
```
Comment (jfgrimm) [inline easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-gompi-2020b.eb:25]: how about adding something like `sanity_check_commands = ['mb <<< %s' % x for x in ['about', 'help']]`?

Comment (jfgrimm) [reply easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-gompi-2020b.eb:25]: although I guess that should go in the easyblock

Comment (boegel) [reply easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-gompi-2020b.eb:25]: Yeah, easyblock is a better place for that, exactly.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3141.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ad91858edef36b5efd93f072fd40c89e for a full test report.

File: easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-gompi-2020b.eb (hunk 1 above)
Comment (jfgrimm) [reply easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-gompi-2020b.eb:25]: https://github.com/easybuilders/easybuild-easyblocks/pull/2727

**Review by branfosj — APPROVED** [review]
lgtm

**Comment by branfosj** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--include-easyblocks-from-pr 2727"

**Comment by jfgrimm** [comment]
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2727
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login2.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d41621c68ff13a72430516a6002bfa87 for a full test report.

**Comment by branfosj** [comment]
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2727"

**Comment by branfosj** [comment]
The failure in https://github.com/easybuilders/easybuild-easyconfigs/pull/15568#issuecomment-1144867923 was in `Clang-11.0.1-GCCcore-10.2.0.eb` and not the easyconfig being added in this PR:
```
== 2022-06-02 13:29:48,255 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): Sanity check failed: no file found at 'lib/libomptarget.rtl.x86_64.so' in /project/def-maintainers/boegelbot/Rocky8/zen2/software/Clang/11.0.1-GCCcore-10.2.0 (at easybuild/easybuild-framework/easybuild/framework/easyblock.py:3461 in _sanity_check_step)
```

We build `Clang-12.0.1-GCCcore-11.2.0.eb` in https://github.com/easybuilders/easybuild-easyconfigs/pull/14068#issuecomment-1145085891 and that went fine. So, I'm not sure what went wrong here but it is not a reason to hold this PR up.

**Comment by branfosj** [comment]
Going in, thanks @boegel!
