### ISSUE TITLE
jax v10.0.1 fails to build with glibc v2.43

### ISSUE THREAD

**Issue by Thyre** [easybuilders/easybuild-easyconfigs#26361]
See https://github.com/easybuilders/easybuild-easyconfigs/pull/26359#issuecomment-4771053114

```
In file included from external/boringssl/src/crypto/fipsmodule/bcm.c:31:
external/boringssl/src/crypto/fipsmodule/../internal.h:857:10: error: returning 'const void *' from a function with result type 'void *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
  857 |   return memchr(s, c, n);
      |          ^~~~~~~~~~~~~~~
/usr/include/string.h:122:3: note: expanded from macro 'memchr'
  122 |   __glibc_const_generic (S, const void *, memchr (S, C, N))
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/cdefs.h:838:3: note: expanded from macro '__glibc_const_generic'
  838 |   _Generic (0 ? (PTR) : (void *) 1,                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  839 |             const void *: (CTYPE) (CALL),               \
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  840 |             default: CALL)
      |             ~~~~~~~~~~~~~~
1 error generated.
```

While this does not affect most Linux distributions HPC systems, this does affect EESSI and some recent distros such as Ubuntu 26.04 LTS and Fedora 44.
