### PR TITLE
{lang}[foss/2021b] R 4.2.0

### PR DESCRIPTION
**Pull request by fizwit**
(created using `eb --new-pr`)

* [x] https://github.com/easybuilders/easybuild-easyblocks/pull/2713

### CODE REVIEW

**Comment by fizwit** [comment]
9 new packages have been added as dependencies from updated libraries. Total exts_list is now 1053.

```
                  hardhat : 0.2.0 from recipes               (add) [1044, 195]
                  recipes : 0.1.17 -> 0.2.0               (update) [1044, 196]

                  weights : 1.0.4 from TraMineR              (add) [1044, 414]
                 TraMineR : 2.2-2 -> 2.2-3                (update) [1044, 415]

          spatstat.random : 2.2-0 from spatstat.core         (add) [1044, 489]
            spatstat.core : 2.3-0 -> 2.4-2                (update) [1044, 490]

                   rlemon : 0.2.0 from optmatch              (add) [1044, 697]
                 optmatch : 0.9-15 -> 0.10.0              (update) [1044, 698]

                 RSpectra : 0.16-1 from SKAT                 (add) [1044, 700]
                     SKAT : 2.0.1 -> 2.2.4                (update) [1044, 701]

                 RcppTOML : 0.1.7 from reticulate            (add) [1044, 718]
               reticulate : 1.22 -> 1.24                  (update) [1044, 719]

                  metadat : 1.2-0 from metafor               (add) [1044, 955]
                  metafor : 3.0-2 -> 3.4-0                (update) [1044, 956]

                   admisc : 0.26 from polycor                (add) [1044, 983]
                  polycor : 0.7-10 -> 0.8-1               (update) [1044, 984]

                    furrr : 0.2.3 from broom.mixed           (add) [1044, 989]
              broom.mixed : 0.2.7 -> 0.2.9.4              (update) [1044, 990]
```

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/5f21ddd36e6ecefb6a0b855284a46447 for a full test report.

**Comment by verdurin** [comment]
Checksum error (of course):
```
== 2022-04-28 08:53:47,405 filetools.py:1306 DEBUG Computed sha256 checksum for /eb/maint/sources/r/R/extensions/rda_1.0.2-2.1.tar.gz: 6918b62f51252b57f2c05b99debef6136b370f594dc3ae6466268e4c35578ef8 (correct checksum: eea3a51a2e132a023146bfbc0c384f5373eb3ea2b61743d7658be86a5b04949e)
== 2022-04-28 08:53:47,420 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Checksum verification for extension source rda_1.0.2-2.1.tar.gz failed (at easybuild/framework/easyblock.py:640 in collect_exts_file_info)
```

**Comment by fizwit** [comment]
rda and AnalyzeFMRI  been removed from CRAN. This might be due to the fact that there are build issues and the maintainers have not updated the packages to reflect that they have not tested with 4.2.  The packages could re-emerge as the authors fix deficiencies. I'm not sure how to handle these packages, they were available when I started working with 4.2 but have since been pulled. rda is available from the archives.

**Review by branfosj — CHANGES_REQUESTED** [review]
These suggested changes:
* restores comments that `--inject-checksums` removes
* add an alternative checksum for `rda`
* add and update recently added packages

I've set off a local build with these changes to check that I've not broekn it ...

File: easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb [hunk 1]
```diff
@@ -0,0 +1,3234 @@
...
+    }),
+    ('metafor', '3.4-0', {
+        'checksums': ['92e1bc21c4d135b6e651fbefc4b40666fc02c66a6a4f6f28effee0e73a21c26e'],
+    }),
+    ('fmri', '1.9.6', {
+        'checksums': ['7614290d880667512744d3450480a670cc38abdb270f3f776ac9a17a793f07f2'],
+    }),
+    ('AnalyzeFMRI', '1.1-24', {
+        'checksums': ['0d2acfe9ce8f25eb5cc9e6ef1db3ea8e232a31d46a95e50914489b1997e17062'],
+    }),
```
Comment (branfosj) [inline easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb:2944]:
```suggestion
    ('AnalyzeFMRI', '1.1-24', {
        'checksums': ['0d2acfe9ce8f25eb5cc9e6ef1db3ea8e232a31d46a95e50914489b1997e17062'],
    }),
```

This fails because `src/spatial.filters.non.linear.c` has `#include <S.h>`

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

File: easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb [hunk 2]
```diff
@@ -0,0 +1,3329 @@
...
+    ('threejs', '0.3.3', {
+        'checksums': ['76c759c8b20fb34f4f7a01cbd1b961296e1f19f4df6dded69aae7f1bca80219c'],
+    }),
+    ('LaplacesDemon', '16.1.6', {
+        'checksums': ['57b53882fd7a195b38bbdbbf0b17745405eb3159b1b42f7f11ce80c78ab94eb7'],
+    }),
+    ('rda', '1.0.2-2.1', {
+        'checksums': ['eea3a51a2e132a023146bfbc0c384f5373eb3ea2b61743d7658be86a5b04949e'],
+    }),
```
Comment (branfosj) [inline easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb:2440]:
```suggestion
    ('rda', '1.0.2-2.1', {
        'checksums': [('6918b62f51252b57f2c05b99debef6136b370f594dc3ae6466268e4c35578ef8',
                       'eea3a51a2e132a023146bfbc0c384f5373eb3ea2b61743d7658be86a5b04949e')],
    }),
```

**Comment by branfosj** [comment]
@boegelbot please test @ generoso

**Comment by branfosj** [comment]
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/88e4160050c6138f9d37d523a10f76ad for a full test report.

**Comment by boegel** [comment]
@boegelbot please test @ jsc-zen2
EB_ARGS="--parallel-extensions-install --experimental"

**Comment by verdurin** [comment]
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/ef871a06aa75a4117e6d9e4ee4c45ae6 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2602.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/5f6a05e2f30abfe12a8eff70f6804292 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3119.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8252d5ecf7e5779bd69f720d9445eb20 for a full test report.

**Comment by boegel** [comment]
My test reports were running with an outdated easyblocks installation that didn't include https://github.com/easybuilders/easybuild-easyblocks/pull/2713 yet; likewise for @verdurin

I'll upload a new test report with `--module-only` after updating my easyblocks installation, and then get this merged.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2602.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/c79bff4953bb6844e830e584fe40b26a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2602.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a3acebd4bb1aedc7c975f2e73f0f84b8 for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/096ae750629bd9069c2239be7fd1011a for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3589.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/d51ca78f94348ec392f9844ed34b9b0f for a full test report.

**Comment by boegel** [comment]
Going in, thanks @fizwit!

**Comment by verdurin** [comment]
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/87913fad3c165805d2d8fe46630271bf for a full test report.

**Comment by fizwit** [comment]
thanks, @boegel @verdurin @branfosj for the help.
I have contacted the maintainers of AnalyzeFMRI with the patch and they have responded. I hope that it makes it back into CRAN.

**Comment by boegel** [comment]
@fizwit You have a patch for `AnalyzeFMRI` which makes it compatible with R v4.2.0?
If so, why don't we use that to add `AnalyzeFMRI` back as extension?
