### ISSUE TITLE
nvcc is failing to build basic NVidia code on CentOS 7.9 following an OS update

### ISSUE THREAD

**Issue by dithwick** [easybuilders/easybuild-easyconfigs#12107]
We received a report from a user saying that a basic Nvidia example code (namely add.cu from https://developer.nvidia.com/blog/even-easier-introduction-cuda/) was failing to build when it previously built successfully. This was on CentOS 7.9 with the latest updates installed including those released by CentOS on 04/02/2021.

After loading the GCC/8.3.0 and CUDA/10.1.243 modules the following error is produced:

```
~/.local/easybuild/desktop/2018/software/CUDA/10.1.243-GCC-8.3.0/bin/nvcc add.cu -o add_cuda
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h: In member function ‘std::size_t std::hash<float>::operator()(float) const’:
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h:232:22: error: expected ‘)’ before numeric constant
  return __val != 0.0f ? std::_Hash_impl::hash(__val) : 0;
                  ~   ^~~
                      )
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h:232:15: error: invalid operands of types ‘float’ and ‘double(const char*) throw ()’ {aka ‘double(const char*)’} to binary ‘operator!=’
  return __val != 0.0f ? std::_Hash_impl::hash(__val) : 0;
         ~~~~~~^~~~~~~~~~
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h:232:64: error: expected ‘)’ before ‘;’ token
  return __val != 0.0f ? std::_Hash_impl::hash(__val) : 0;
        ~                                                       ^
                                                                )
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h: In member function ‘std::size_t std::hash<double>::operator()(double) const’:
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h:244:22: error: expected ‘)’ before numeric constant
  return __val != 0.0 ? std::_Hash_impl::hash(__val) : 0;
                  ~   ^~
                      )
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h:244:15: error: invalid operands of types ‘double’ and ‘double(const char*) throw ()’ {aka ‘double(const char*)’} to binary ‘operator!=’
  return __val != 0.0 ? std::_Hash_impl::hash(__val) : 0;
         ~~~~~~^~~~~~~~~
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/8.3.0/include/c++/8.3.0/bits/functional_hash.h:244:63: error: expected ‘)’ before ‘;’ token
  return __val != 0.0 ? std::_Hash_impl::hash(__val) : 0;
        ~                                                      ^
                                                               )
add.cu: In function ‘int main()’:
add.cu:33:22: error: expected ‘)’ before numeric constant
   float maxError = 0.0f;
                  ~   ^~~
                      )
add.cu:33:25: error: cannot convert ‘double (*)(const char*) throw ()’ {aka ‘double (*)(const char*)’} to ‘float’ in initialization
   float maxError = 0.0f;
```
I was able to reproduce this error and rebuilding GCCcore, binutils or CUDA did not resolve the issue. I was able to reproduce the error with fosscuda/2019b, gcccuda/2019b. With fosscuda2020a/b the error was slightly different:
```

/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h: In member function 'std::size_t std::hash<float>::operator()(float) const':
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h:237:22: error: expected ')' before numeric constant
  237 |  return __val != 0.0f ? std::_Hash_impl::hash(__val) : 0;
      |                  ~   ^~~
      |                      )
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h:237:15: error: invalid operands of types 'float' and 'double(const char*) throw ()' {aka 'double(
const char*)'} to binary 'operator!='
  237 |  return __val != 0.0f ? std::_Hash_impl::hash(__val) : 0;
      |         ~~~~~ ^~ ~~~~~~~
      |         |         |
      |         float     double(const char*) throw () {aka double(const char*)}
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h:237:64: error: expected ')' before ';' token
  237 |  return __val != 0.0f ? std::_Hash_impl::hash(__val) : 0;
      |        ~                                                       ^
      |                                                                )
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h: In member function 'std::size_t std::hash<double>::operator()(double) const':
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h:249:22: error: expected ')' before numeric constant
  249 |  return __val != 0.0 ? std::_Hash_impl::hash(__val) : 0;
      |                  ~   ^~
      |                      )
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h:249:15: error: invalid operands of types 'double' and 'double(const char*) throw ()' {aka 'double
(const char*)'} to binary 'operator!='
  249 |  return __val != 0.0 ? std::_Hash_impl::hash(__val) : 0;
      |         ~~~~~ ^~ ~~~~~~
      |         |         |
      |         double    double(const char*) throw () {aka double(const char*)}
/home/csc/user/.local/easybuild/desktop/2018/software/GCCcore/9.3.0/include/c++/9.3.0/bits/functional_hash.h:249:63: error: expected ')' before ';' token
  249 |  return __val != 0.0 ? std::_Hash_impl::hash(__val) : 0;
      |        ~                                                      ^
      |                                                               )
add.cu: In function 'int main()':
add.cu:33:22: error: expected ')' before numeric constant
   33 |   float maxError = 0.0f;
      |                  ~   ^~~
      |                      )
add.cu:33:19: error: cannot convert 'double ()(const char) throw ()' {aka 'double ()(const char)'} to 'float' in initialization
   33 |   float maxError = 0.0f;
      |                  ~^~~~~~
      |                   |
      |                   double ()(const char) throw () {aka double ()(const char)}
```

**Comment by dithwick** [comment]
Testing by others (see Slack) suggests that the problem may relate to the glibc 2.17-322.el7_9 update since it appears to build fine with glibc-2.17-317.el7.x86_64.

**Comment by dithwick** [comment]
A bug report has been found on the CUDA forums - https://forums.developer.nvidia.com/t/rhel-centos-update-causes-nvcc-to-fail/167693

**Comment by dithwick** [comment]
The problem doesn't seem to occur on:

- CentOS 6.10
- CentOS 8
- Ubuntu 16.04

The changelog for glibc between the packages is:

```
* Wed Jan 06 2021 Carlos O'Donell <carlos@redhat.com> - 2.17-322
- Enable file-based IFUNC selection on NVMe devices (#1883162)
* Wed Jan 06 2021 Carlos O'Donell <carlos@redhat.com> - 2.17-321
- CVE-2020-10029: Prevent stack corruption from crafted input in cosl, sinl,
  sincosl, and tanl function. (#1812119)
* Tue Jan 05 2021 Carlos O'Donell <carlos@redhat.com> - 2.17-320
- CVE-2020-29573: Harden printf family of functions (#1869380)
* Tue Jan 05 2021 Carlos O'Donell <carlos@redhat.com> - 2.17-319
- Revert fix for #1772307 to improve Intel Xeon performance (#1889977)
* Tue Jan 05 2021 Carlos O'Donell <carlos@redhat.com> - 2.17-318
- CVE-2019-25013: Fix EUC-KR conversion module defect (#1912543)
```

**Comment by zao** [comment]
If I put the `libc.so.6` files from the -317 rpm in `LD_LIBRARY_PATH` the nvcc compile of my test case succeeds, so it's something compiled into the glibc that has changed behaviour.

**Comment by dithwick** [comment]
Could this be the issue https://bugzilla.redhat.com/show_bug.cgi?id=1925204

**Comment by boegel** [comment]
Possibly related (same underlying cause): #12105

**Comment by mboisson** [comment]
One of our analyst has hit a very similar issue on our build node (but not on our clusters), so maybe we are able to provide information to allow pin-pointing the issue.

**Comment by mboisson** [comment]
The following code : 
```
$ cat test.cu
int main() {
    return 0;
}
``` 

which we then compile with 
```
nvcc test.cu
``` 

produces the exact same error in the following context for us : 
* CentOS 7.9 + Gentoo + Cuda 11

but does not produce the error in : 
* CentOS 7.8 + Gentoo + Cuda 11
* CentOS 7.9 + Nix + Cuda 8, 9, 10

**Comment by dithwick** [comment]
glibc-2.17-323.el7_9.x86_64 has just started rolling out via the CentOS mirrors and this resolves the problem for me. The one item in the changelog is:

```
* Fri Feb 05 2021 Siddhesh Poyarekar <siddhesh@redhat.com> - 2.17-323
- Fix isnanl check in printf. (#1925204)

```
I would check if updating your build nodes with this glibc version fixes it.

**Comment by zao** [comment]
nvcc can now compile again on my CentOS 7 VM with the -323 glibc.

**Comment by mboisson** [comment]
We also figured out why it failed with our Gentoo overlay and CUDA 11 : we forgot to patch nvcc to use the Gentoo libraries rather than the OS ones.

**Comment by dithwick** [comment]
I'm not sure if this ticket needs to stay open. I think to summarise for anyone who comes across this issue on CentOS 7, don't use glibc-2.17-322.el7_9.x86_64, either downgrade or ideally upgrade to -323 or later.
