### ISSUE TITLE
Qt5/5.13.1-GCCcore-8.3.0 depends on JasPer.

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyconfigs#9274]
I'm trying to build Qt5/5.13.1-GCCcore-8.3.0 on RHEL8 and it fails on:

```
qjp2handler.cpp:47:10: fatal error: jasper/jasper.h: No such file or directory
 #include <jasper/jasper.h>
          ^~~~~~~~~~~~~~~~~
```

JasPer is not set as a dependency for Qt5/5.13.1-GCCcore-8.3.0 and there is no JasPer/2.0.14-GCCcore-8.3.0 available. I'm mostly wondering if this is a RHEL8 issue since this hasn't been seen before? There is a jasper-devel package available in the OS, but there are no osdeps either in the package.

For what its worth, JasPer/2.0.14 builds fine with GCCcore 8.3.0 and Qt5/5.13.1-GCCcore-8.3.0 builds fine once JasPer/2.0.14-GCCcore-8.3.0 is installed and added as a dependency.

**Comment by boegel** [comment]
This was probably overlooked because most people have JasPer installed in the OS?

Are you up for opening a pull request to add the missing dep and fix this issue?

**Comment by terjekv** [comment]
Seems I missed a binutils dependency in the patch. Good work on the CI!

**Comment by terjekv** [comment]
Hm, I'm not sure what this CI error stems from.

```
/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
.
======================================================================
ERROR: test_dep_graph (test.easyconfigs.easyconfigs.EasyConfigTest)
Unit test that builds a full dependency graph.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 132, in test_dep_graph
    dep_graph(fn, EasyConfigTest.ordered_specs)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/easybuild/framework/easyconfig/tools.py", line 210, in dep_graph
    dgr.add_edge((spec['module'], dep))
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/pygraph/classes/digraph.py", line 169, in add_edge
    raise AdditionError("Edge (%s, %s) already in digraph" % (u, v))
pygraph.classes.exceptions.AdditionError: Edge (Qt5/5.13.1-GCCcore-8.3.0, JasPer/2.0.14-GCCcore-8.3.0) already in digraph
----------------------------------------------------------------------
Ran 8674 tests in 443.516s
FAILED (errors=1)
ERROR: Not all tests were successful.
Found 8665 easyconfigs...

List of changed easyconfig files in this PR: JasPer-2.0.14-GCCcore-8.3.0.eb
Qt5-5.13.1-GCCcore-8.3.0.eb
##[error]Process completed with exit code 2.
```

**Comment by boegel** [comment]
@terjekv The issue is that you're adding `JasPer` twice to the dep graph, see https://github.com/easybuilders/easybuild-easyconfigs/pull/9311#discussion_r347081999
