### ISSUE TITLE
"Failed to modify UD QP to INIT on mlx5_0: Operation not permitted" error with OpenMPI after updating to OFED 23.10

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#20233]
After updating to OFED 23.10, we had several reports of people running this cryptic error:

```
Failed to modify UD QP to INIT on mlx5_0: Operation not permitted
```

The problem does not occur consistently (@hajgato has more details here).

https://github.com/openucx/ucx/issues/9468 suggests that updating to a more recent OFED may help, but it doesn't.

**Comment by boegel** [comment]
We've pinned this down to the libfabric dependency we include with OpenMPI: when libfabric is removed as a dependency, the problem no longer occurs.

This requires rebuilding OpenMPI, so that's painful on a production system.

As a workaround, you can instruct OpenMPI to not use libfabric by passing the following options to `mpirun`:

```
mpirun -mca pml ucx -mca btl '^uct,ofi' -mca mtl '^ofi'
```

Or equivalently, you can set the following environment variables:

```
export OMPI_MCA_btl='^uct,ofi'
export OMPI_MCA_pml='ucx'
export OMPI_MCA_mtl='^ofi'
```

**Comment by boegel** [comment]
SURF (@casparvl) also saw a very similar issue, they worked around it by setting `$FI_PROVIDER` to `verbs`...

The error there was `Invalid argument` though, more similar to what was reported in https://github.com/openucx/ucx/issues/9468

**Comment by branfosj** [comment]
I've not seen this, but we added the following in December 2021 because of another issue we'd seen
```
            # avoid libfabric warning "unknown link width 0x10"
            # see https://github.com/ComputeCanada/software-stack-config/pull/19
            setenv OMPI_MCA_mtl "^ofi"
            setenv OMPI_MCA_btl "^openib,ofi"
```

**Comment by casparvl** [comment]
Yep, we get these:

> # avoid libfabric warning "unknown link width 0x10"

As well regularly. We also solved it by setting those envrionment variables (I believe, would need to check what we set _exactly_)

**Comment by casparvl** [comment]
More detail on what I hit [here](https://github.com/EESSI/software-layer/issues/456#issuecomment-1976784523) btw

**Comment by jhein32** [comment]
I am wondering what the status of this is.  We recently upgraded to MLNX_OFED_LINUX-24.07-0.6.1.0 (OFED-24.07-0.6.1) and are now seeing this.  The above export:

> export OMPI_MCA_btl='^uct,ofi'
export OMPI_MCA_pml='ucx'
export OMPI_MCA_mtl='^ofi'

still seems to solve this.  Are there any plans to get this closed or are we waiting for something external?

**Comment by PhoenixEmik** [comment]
We are using MLNX_OFED_LINUX-24.10-2.1.8.0 and get some similar errors:
```
Unable to initialize verbs NIC /sys/class/infiniband/mlx5_1 (unit 1:0)
Unable to open mlx5_1: Operation not permitted
```
Setting the two environment variables also solves the issue.
```
export OMPI_MCA_btl='^uct,ofi'
export OMPI_MCA_mtl='^ofi'
```
However, we have to avoid `export OMPI_MCA_pml='ucx'` because it causes another error:
```
PML ucx cannot be selected
```

**Comment by Flamefire** [comment]
I can reproduce this with a simple MPI hello-world program. Sometimes I need to run it 2-3 times before I get the error and often it would hang for a while.

I don't see the issue in OpenMPI 5.x anymore. Actually libfabric 1.21 works, even with OpenMPI 4.1.6. (I rebuilt that module with an updated libfabric)

**Comment by sassy-crick** [comment]
> I can reproduce this with a simple MPI hello-world program. Sometimes I need to run it 2-3 times before I get the error and often it would hang for a while.
> 
> I don't see the issue in OpenMPI 5.x anymore. Actually libfabric 1.21 works, even with OpenMPI 4.1.6. (I rebuilt that module with an updated libfabric)

Same here on our RHEL-9.6 release with `ofed-scripts-25.07-OFED.25.07.0.9.7.x86_64` I had this issue, which seems to have vanished when I upgrade to `libfabric 1.22`. However, like @Flamefire it was difficult to reproduce. That said, the cluster is still moving so something in the background could have changed.
Note: `libfabric-2.x` does not seem to work with `OpenMPI 4.1.6` as I get a compilation error:
```
mtl_ofi_request.h:19:30: error: expected expression before ‘struct’
   19 |     container_of((_ptr_ctx), struct ompi_mtl_ofi_request_t, ctx)
      |                              ^~~~~~
mtl_ofi.h:161:23: note: in expansion of macro ‘TO_OFI_REQ’
  161 |             ofi_req = TO_OFI_REQ(error.op_context);
```
