### PR TITLE
Fix #9274, Qt5/5.13.1-GCCcore-8.3.0 depends on JasPer.

### LINKED ISSUE #9274: Qt5/5.13.1-GCCcore-8.3.0 depends on JasPer.
I'm trying to build Qt5/5.13.1-GCCcore-8.3.0 on RHEL8 and it fails on:

```
qjp2handler.cpp:47:10: fatal error: jasper/jasper.h: No such file or directory
 #include <jasper/jasper.h>
          ^~~~~~~~~~~~~~~~~
```

JasPer is not set as a dependency for Qt5/5.13.1-GCCcore-8.3.0 and there is no JasPer/2.0.14-GCCcore-8.3.0 available. I'm mostly wondering if this is a RHEL8 issue since this hasn't been seen before? There is a jasper-devel package available in the OS, but there are no osdeps either in the package.

For what its worth, JasPer/2.0.14 builds fine with GCCcore 8.3.0 and Qt5/5.13.1-GCCcore-8.3.0 builds fine once JasPer/2.0.14-GCCcore-8.3.0 is installed and added as a dependency.

### PR DESCRIPTION
**Pull request by terjekv**
- Qt5 depends on JasPer, which is missing from the spec.
  - Add JasPer for GCCcore-8.3.0.
  - Resolves #9274

### CODE REVIEW

**Comment by boegel** [comment]
@terjekv Any idea if this is also relevant for older versions of `Qt5`?

**Comment by boegel** [comment]
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/c98d71281d238a5ded2a54cf26ef1fad for a full test report.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node3146.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/d001af0ac40c57c74e2d3eeacfd2ced7 for a full test report.

**Comment by terjekv** [comment]
@boegel I’m not creating where else this applies. I can take a look.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
node2630.swalot.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/407d509cde52c5310f157aa4eb727082 for a full test report.

**Comment by boegel** [comment]
Going in, thanks @terjekv!

**Comment by boegel** [comment]
@terjekv If this is relevant for older `Qt5` versions too, we should apply the same fix there, please let us know.

**Comment by boegel** [comment]
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/6c07a63a51849c8e38dd27d9867d145c for a full test report.
