### PR TITLE
{bio}[foss/2020b] QIIME2 v2022.8 w/ Python 3.8.6 (WIP)

### PR DESCRIPTION
**Pull request by migueldiascosta**
(created using `eb --new-pr`)

requires:

- [x] #16941
- [x] ~~#16942~~ #17161
- [x] #16943

(as mentioned in the linked PRs, the reason to use 2020b is that QIIME v2022.8 w/ Python >= 3.9 fails simple tasks, related to the Python `ast` module)

### CODE REVIEW

**Comment by migueldiascosta** [comment]
hm, using the distributed pretrained classifiers requires scikit-learn 0.24.1 specifically (https://github.com/qiime2/docs/blob/master/source/data-resources.rst)

not sure that's worth the dependency variant exception (would also affect scikit-bio and umap-learn)

**Review by lexming — CHANGES_REQUESTED** [review]
@migueldiascosta tests fail because two different versions of numba and LLVM get pulled in the dependency tree:
* R > Mesa > LLVM-11
* umap-learn > numba-0.52 > LLVM-10

The easiest solution seems to be to upgrade umap-learn to v0.5.3 which is compatible with numba v0.53 and LLVM 11. I made a PR for it in https://github.com/easybuilders/easybuild-easyconfigs/pull/17161

**Review by lexming — CHANGES_REQUESTED** [review]
QIIME2 also depends on MAFFT. See https://docs.qiime2.org/2023.2/tutorials/moving-pictures/

**Comment by migueldiascosta** [comment]
this is still WIP, I'll check if newer versions of QIIME2 still have problems with Python > 3.8, if they don't I'll submit a PR with a more recent toolchain

**Comment by migueldiascosta** [comment]
Nope, with QIIME2 2023.2 and Python 3.9.6 I still get e.g.

```bash
$ qiime tools validate $EBROOTQIIME2/lib/python3.9/site-packages/q2_sample_classifier/tests/data/vaw.qza
Traceback (most recent call last):
  File "$EBROOTQIIME2/lib/python3.9/site-packages/q2cli/builtin/tools.py", line 555, in validate
    result = qiime2.sdk.Result.load(path)
  File "$EBROOTQIIME2/lib/python3.9/site-packages/qiime2/sdk/result.py", line 79, in load
    archiver = archive.Archiver.load(filepath)
  File "$EBROOTQIIME2/lib/python3.9/site-packages/qiime2/core/archive/archiver.py", line 372, in load
    ref = cls(data_path, process_alias, Format(rec), cache)
  File "$EBROOTQIIME2/lib/python3.9/site-packages/qiime2/core/archive/format/v1.py", line 29, in __init__
    super().__init__(archive_record)
  File "$EBROOTQIIME2/lib/python3.9/site-packages/qiime2/core/archive/format/v0.py", line 72, in __init__
    self.type = sdk.parse_type(type)
  File "$EBROOTQIIME2/lib/python3.9/site-packages/qiime2/sdk/util.py", line 68, in parse_type
    type_expr = _parse.ast_to_type(_parse.string_to_ast(string))
  File "$EBROOTQIIME2/lib/python3.9/site-packages/qiime2/core/type/parse.py", line 32, in string_to_ast
    return _expr(expr.value)
  File "$EBROOTQIIME2/lib/python3.9/site-packages/qiime2/core/type/parse.py", line 47, in _expr
    field_expr = expr.slice.value
AttributeError: 'Name' object has no attribute 'value'

There was a problem loading $EBROOTQIIME2/lib/python3.9/site-packages/q2_sample_classifier/tests/data/vaw.qza as a QIIME 2 Result:

  'Name' object has no attribute 'value'

See above for debug info.
```

(this works with Python 3.8.6)

**Comment by migueldiascosta** [comment]
superseded by https://github.com/easybuilders/easybuild-easyconfigs/pull/18407, where the issue with python 3.9 ast was fixed, thanks @smoors !
