### ISSUE TITLE
Qt5-5.13.1-GCCcore-8.3.0.eb undefined reference to 'qfloat16::mantissatable'

### ISSUE THREAD

**Issue by zdemat** [easybuilders/easybuild-easyconfigs#10332]
Hi,

there is a missing symbol float16 ```mantissatable``` in Qt5-5.13.1 build with GCCcore-8.3.0.
This error will appear when trying to use ```qfloat16``` datatype. A simple test to reproduce:

1. copy example $EBROOTQT5/examples/widgets/mainwindows/application/
2. add to main.cpp
```
// main.cpp
#include "qfloat16.h"
#include "stdio.h"

qfloat16 f=0.1;
printf("%f\n", (double)f);
```
3. ```qmake application.pro; make```

```
main.o:main.cpp:function main: error: undefined reference to 'qfloat16::shifttable'
main.o:main.cpp:function main: error: undefined reference to 'qfloat16::basetable'
main.o:main.cpp:function main: error: undefined reference to 'qfloat16::offsettable'
main.o:main.cpp:function main: error: undefined reference to 'qfloat16::exponenttable'
main.o:main.cpp:function main: error: undefined reference to 'qfloat16::mantissatable'
```

- qloat16 is defined in ```qtbase/src/corelib/global/qfloat16.h```
- implementation of ```inline qfloat16::operator float() const``` is using mantissatable depending on defined ```QT_COMPILER_SUPPORTS_F16C```, ```__F16C__``` and  ```__ARM_FP16_FORMAT_IEEE```
- ```mantissatable``` is implemented in an *generator*: ```qtbase/src/tools/qfloat16-tables/gen_qfloat16_tables.cpp```
- unfortunately the preprocessor conditions in generator are inconsistent with the header
- the issue is resolved in Qt5-5.14 in ```qtbase/util/qfloat16-tables/gen_qfloat16_tables.cpp```

The issue is that with this ```qfloat16``` broken __PyQt5-5.13 cannot be build__

The patch porting the fix from 5.14 is very simple and straightforward.

**Comment by boegel** [comment]
Fixed in #10425, thanks for looking into this @zdemat!
