### ISSUE TITLE
Scorep 6.0 in gompi 2020a doesn't work with binutils 2.34

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#11105]
The current Score-P-6.0-gompi-2020a.eb required for Scalasca doesn't work with the binutils 2.34 in gompi 2020a, the `bfd_get_section_flags` et.al. depreciation issue. 

Hear say has it, that this will be fixed in the next Score-P release.  As a bug fix we need to move the Score-P version in 2020a once the new version (or a beta) becomes publicly available.

Perhaps it is an idea to retire Score-P/Scalasca from the current distribution until the fix is available.

**Comment by jhein32** [comment]
I am happy to confirm that the PR #11123 fixes the issue I was facing.

Is it me who closes the issue report?

**Comment by boegel** [comment]
@jhein32 Do you mind mentioning the error messages you ran into? That's helpful for people who run into them and start searching for solutions (if they hit this issue they'll know rebuilding `Score-P` with the patch included in #11123 should fix that problem).

**Comment by jhein32** [comment]
With out the patch we got error message like:

`libscorep_measurement.so: error: undefined reference to 'bfd_get_section_flags'`

at the link step when building instrumented executable with the instrumenter`scorep` or the depreciated scalasca instrumenter `skin`.
